### ISSUE TITLE
Error loading deploy information

### ISSUE THREAD

**Issue by iaguilera14** [ionic-team/cordova-plugin-ionic#103]
I have installed 5.0rc3 and get this error. I am trying to determine if this plugin is what is throwing this error. My app does function fine after this error. 

`Error loading deploy information.
TypeError: plugin.deploy.info is not a function. (In 'plugin.deploy.info(function(res){resolve(res)},function(err){reject(err)})', 'plugin.deploy.info' is undefined`

cordova plugin ls

> cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.0 "Notification"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.0.0-rc.3 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.1 "Launch Navigator"

**Comment by nphyatt** [comment]
@iaguilera14 That is correct the `info` function is no longer available on `v5` and has been deprecated in favor of `getConfiguration`. 

You can see the deprecated methods & the new methods in our [API docs](https://ionicframework.com/docs/pro/deploy/api/#methods) and you can look up the old ones you might be using (such as `info()`) and find the link to the function you can replace them with.

For example: 
![image](https://user-images.githubusercontent.com/6487450/43277650-4a04d63c-90ce-11e8-991d-607b45f78966.png)

If you need more help upgrading your app this [migration guide & video](https://ionicframework.com/docs/pro/deploy/tutorials/#upgrading-to-the-new-deploy-plugin) should help.

**Comment by iaguilera14** [comment]
My missing part was not upgrading  @ionic/pro. After I did that the error went away. Thanks for you help!
