### ISSUE TITLE
suggestion: refactor for app_id  usage in deploy api calls

### ISSUE THREAD

**Issue by jaapjanfrans** [ionic-team/cordova-plugin-ionic#11]
Most deploy API methods feature the app_id string as the first argument. 

I imagine that in most cases when people use the plugin in manual mode (no auto update), they have one app_id that they'd use; the app_id of their own application.

I'd suggest to remove app_id as argument from all API methods except for init. that way, you only have to set it once and let the plugin store it for use when other api calls are being done.

**Comment by Fuiste** [comment]
This is a good call, and is something I'm addressing in version 2.0.0 of the plugin, which should be out within a week.

Check out the progress here https://github.com/ionic-team/cordova-plugin-ionic/pull/13

**Comment by Fuiste** [comment]
This should be fixed in version 2.0.0, thanks for the heads up!
