### ISSUE TITLE
Ionic Deploy API cannot handle null device_id

### ISSUE THREAD

**Issue by connor-odoherty** [ionic-team/cordova-plugin-ionic#111]
When I download my v5 Ionic app fresh onto the device (no instance of the app currently downloaded), deploy and everything else works beautifully.

However, when attempting to install a new v5 binary onto an old binary, deploy completely breaks with error: 

`ERROR: Unhandled Promise rejection: Error Status 422: An error occurred while validating the request parameters. ; Zone: <root> ; Task: Promise.then ; Value: Error: Error Status 422: An error occurred while validating the request parameters. http://localhost:8080/plugins/cordova-plugin-ionic/dist/common.js:170:28 `

The failure specifically occurs during the checkForUpdates method. Digging a little deeper, I see that checkForUpdates POSTs a request using a body object. 
```
const device_details = { 
  binary_version: appInfo.bundleVersion, 
  device_id: appInfo.device, 
  platform: appInfo.platform, 
  platform_version: appInfo.platformVersion, 
  snapshot: prefs.currentVersionId 
};
```
```
const body = { 
  channel_name: prefs.channel, 
  app_id: prefs.appId, 
  device: device_details, 
  plugin_version: this.PLUGIN_VERSION, 
  manifest: true 
};
```

When I download my v5 binary onto an old binary, the device_id is null. I believe THIS is what is causing the failure. If I hardcode the device_id, everything works as expected.

Adding some logging to the source, I see:

```
{"error":
  {"link":null,"message":"An error occurred while validating the request parameters.","type":"UnprocessableEntity","details":[{"error_type":"invalid_guid","parameter":"device.device_id","errors":["Not a valid UUID."]}]},"meta":{"status":422,"request_id":null,"version":"2.0.0-sdlc-beta.0"}}
```

Is this an issue on my end? Or does the deploy API need to be changed to better handle a null device_id? It's odd to me that device ID is null on startup. As far as I can tell, the issue lies purely in deviceInfo. Does it make sense that the device ID was not set in older builds?

It looks like 

```
Got app info: {
    bundleName = "com.jetinsight.crew";
    bundleVersion = "2.1.0";
    device = "";
    platform = ios;
    platformVersion = "11.4.1";
    version = "2.1.0";
}
```

is happening before the device.ready finishes, so that seems like an issue too.

https://github.com/ionic-team/cordova-plugin-ionic/blob/d2f80f6c96584a49d066692819fde0146ddb75cb/www/common.ts#L142

My Ionic Info:

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : browser 5.0.3 ios 4.5.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v10.7.0
    npm        : 6.2.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by nphyatt** [comment]
Thank @connor-odoherty looks like it was an issue where our API couldn't handle an explicitly `null` device id. I've updated and release a fix on the API so it should work correctly now. Let me know if you still have issues.

**Comment by connor-odoherty** [comment]
@nphyatt Just confirmed my suspicions, the device uuid is getting set to the empty string, so it still fails. When I hardcode in null, deploy works.

Could you patch in a handler for the empty string?

**Comment by Fuiste** [comment]
@connor-odoherty I've just published a new release of the plugin to the `rc` tag that addresses the binary copy issue.  I'm finishing up tests on my end, and should all go well I'll release 5.0.4 today.

Feel free to give it a try in the meantime!

**Comment by connor-odoherty** [comment]
@Fuiste Works beautifully, thanks for working hard and getting these patches out!

**Comment by Bengejd** [comment]
@connor-odoherty how did you install from `5.0.5 rc`?

**Comment by Fuiste** [comment]
Releasing 5.0.5 right now, glad it worked for you!
