### ISSUE TITLE
Unexpected token { in device with android 6.0 after install the plugin 

### ISSUE THREAD

**Issue by alejandrogkl** [ionic-team/cordova-plugin-ionic#114]
To reproduce:

Create a new tabs project 

```
ionic start myApp tabs
```

add android and run

```
ionic cordova platform add android
ionic cordova run android
```

the app  will work, no errors in the console

then install cordova-plugin-ionic

```
cordova plugin add cordova-plugin-ionic --save --variable APP_ID="APPID" --variable CHANNEL_NAME="Production" --variable UPDATE_METHOD="auto"
``` 

run the app, and then the following errors appears in the console.then app is totally inconsistent.

```
:8080/plugins/cordova-plugin-ionic/dist/common.js:178 Uncaught SyntaxError: Unexpected token {
polyfills.js:3 Uncaught Error: Module cordova-plugin-ionic.common does not exist.

```

is you run the app in a device with android 7.0+ will work as expected.

**Comment by nphyatt** [comment]
We were targeting es6 previously if you use the latest version of the plugin this should be fixed now.
