### ISSUE TITLE
main.js:1 Uncaught SyntaxError: Unexpected end of input 

### ISSUE THREAD

**Issue by ambrosiajun** [ionic-team/cordova-plugin-ionic#117]
hi

few days ago, i have failed to build in ionic cloud,(dashboard) and got the advice from ionic pro to upgrade the lib and api.

we have updated the deploy api, success to upload the code and build but!

after download deploy build and(its manual deployment)

`extractUpdate progress: 94
VM64 main.js:7883 extractUpdate progress: 97
VM64 main.js:7883 extractUpdate progress: 97
VM64 main.js:7883 extractUpdate progress: 97
VM64 main.js:7883 extractUpdate progress: 97
VM64 main.js:7883 extractUpdate progress: 97
VM64 main.js:7883 extractUpdate progress: 97
VM64 main.js:7883 extractUpdate progress: 97
VM64 main.js:7883 extractUpdate progress: 99
VM64 main.js:7883 extractUpdate progress: 99
VM64 main.js:7883 extractUpdate progress: 99
VM64 main.js:7883 extractUpdate progress: 99
VM64 main.js:7883 extractUpdate progress: 99
VM64 main.js:7883 extractUpdate progress: 99
2VM64 main.js:7883 extractUpdate progress: 99
VM64 main.js:7883 extractUpdate progress: 99
VM64 main.js:7883 extractUpdate progress: 100
VM59 common.js:317 Successful recreate
VM59 common.js:369 fetched current base path as www
Navigated to http://localhost:8080/
main.js:1 Uncaught SyntaxError: Unexpected end of input
common.js:369 fetched current base path as /data/user/0/au.com.myspringday.app/files/ionic_built_snapshots/d0a0bd41-66c1-4b50-ba65-a4c817a6fab2
common.js:348 Already running version d0a0bd41-66c1-4b50-ba65-a4c817a6fab2`

cli packages: (C:\Users\AmyJun\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 6.1.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\AmyJun\AppData\Local\Android\Sdk

Misc:

    backend : pro

{
    "name": "springday-mobile",
    "author": "Springday",
    "description": "Springday Mobile",
    "homepage": "https://corporate.myspringday.com.au",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build --prod",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve",
        "lint": "ionic-app-scripts lint"
    },
    "dependencies": {
        "@angular/animations": "5.2.11",
        "@angular/common": "5.2.11",
        "@angular/compiler": "5.2.11",
        "@angular/compiler-cli": "5.2.11",
        "@angular/core": "5.2.11",
        "@angular/forms": "5.2.11",
        "@angular/http": "5.2.11",
        "@angular/platform-browser": "5.2.11",
        "@angular/platform-browser-dynamic": "5.2.11",
        "@angular/platform-server": "^4.4.6",
        "@ionic-native/calendar": "4.11.0",
        "@ionic-native/camera": "4.11.0",
        "@ionic-native/core": "4.11.0",
        "@ionic-native/deeplinks": "4.11.0",
        "@ionic-native/device": "4.11.0",
        "@ionic-native/file": "4.11.0",
        "@ionic-native/file-path": "4.11.0",
        "@ionic-native/firebase": "4.11.0",
        "@ionic-native/health": "4.11.0",
        "@ionic-native/in-app-browser": "4.11.0",
        "@ionic-native/market": "4.11.0",
        "@ionic-native/splash-screen": "4.11.0",
        "@ionic-native/status-bar": "4.11.0",
        "@ionic/pro": "^2.0.3",
        "@ionic/storage": "2.1.3",
        "chart.js": "^2.6.0",
        "cordova-android": "6.4.0",
        "cordova-android-support-gradle-release": "^1.4.4",
        "cordova-ios": "^4.5.4",
        "cordova-plugin-add-swift-support": "^1.7.2",
        "cordova-plugin-calendar": "^5.1.2",
        "cordova-plugin-camera": "^4.0.3",
        "cordova-plugin-compat": "^1.2.0",
        "cordova-plugin-customurlscheme": "^4.3.0",
        "cordova-plugin-device": "^2.0.2",
        "cordova-plugin-file": "^6.0.1",
        "cordova-plugin-filepath": "^1.4.2",
        "cordova-plugin-firebase": "^1.0.5",
        "cordova-plugin-health": "^1.0.5",
        "cordova-plugin-inappbrowser": "^2.0.2",
        "cordova-plugin-ionic": "^5.0.3",
        "cordova-plugin-ionic-webview": "^2.0.2",
        "cordova-plugin-ios-camera-permissions": "^1.2.0",
        "cordova-plugin-market": "^1.2.0",
        "cordova-plugin-splashscreen": "^5.0.2",
        "cordova-plugin-statusbar": "^2.4.2",
        "cordova-plugin-whitelist": "^1.3.3",
        "cordova-sqlite-storage": "^2.3.3",
        "ionic-angular": "3.9.2",
        "ionic-cache": "^2.0.1",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "moment": "^2.20.1",
        "rxjs": "5.5.11",
        "springday-shealth": "file:springday-shealth",
        "sw-toolbox": "3.6.0",
        "webpack": "^3.10.0",
        "zone.js": "0.8.26"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.11",
        "typescript": "2.6.2"
    },
    "cordovaPlugins": [
        "cordova-plugin-device",
        "cordova-plugin-whitelist",
        "cordova-plugin-splashscreen",
        "cordova-plugin-statusbar",
        "ionic-plugin-keyboard"
    ],
    "cordovaPlatforms": [],
    "cordova": {
        "platforms": [
            "android",
            "ios"
        ],
        "plugins": {
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-health": {
                "HEALTH_READ_PERMISSION": "The Springday app pulls in steps, sleep and weight data from HealthKit. The purpose is to present activity data to the user alongside the other wellbeing metrics and services included in the Springday app, including earning 'points' for achieving step milestones and competing in a workplace step challenge.  Historical activity data can be viewed within the profile section of the Springday app.",
                "HEALTH_WRITE_PERMISSION": "The Springday app pulls in steps, sleep and weight data from HealthKit. The purpose is to present activity data to the user alongside the other wellbeing metrics and services included in the Springday app, including earning 'points' for achieving step milestones and competing in a workplace step challenge.  Historical activity data can be viewed within the profile section of the Springday app."
            },
            "cordova-plugin-filepath": {},
            "cordova-plugin-file": {},
            "cordova-plugin-calendar": {
                "CALENDAR_USAGE_DESCRIPTION": "springday event calendar"
            },
            "cordova-sqlite-storage": {},
            "cordova-plugin-customurlscheme": {
                "URL_SCHEME": "springday",
                "ANDROID_SCHEME": " ",
                "ANDROID_HOST": " ",
                "ANDROID_PATHPREFIX": "/"
            },
            "cordova-plugin-market": {},
            "cordova-plugin-device": {},
            "cordova-plugin-compat": {},
            "cordova-plugin-camera": {
                "CAMERA_USAGE_DESCRIPTION": "springday profile picture",
                "PHOTOLIBRARY_USAGE_DESCRIPTION": "springday profile picture"
            },
            "cordova-plugin-ios-camera-permissions": {
                "CAMERA_USAGE_DESCRIPTION": "springday profile picture",
                "PHOTOLIBRARY_USAGE_DESCRIPTION": "springday profile picture",
                "MICROPHONE_USAGE_DESCRIPTION": "This app needs microphone access",
                "PHOTOLIBRARY_ADD_USAGE_DESCRIPTION": "This app needs write-access to photo library"
            },
            "cordova-plugin-ionic-webview": {},
            "cordova-plugin-firebase": {},
            "cordova-plugin-ionic": {
                "APP_ID": "816c9d47",
                "CHANNEL_NAME": "Production",
                "UPDATE_METHOD": "none",
                "UPDATE_API": "https://api.ionicjs.com",
                "MAX_STORE": "2",
                "WARN_DEBUG": "true",
                "MIN_BACKGROUND_DURATION": "30"
            },
            "cordova-android-support-gradle-release": {
                "ANDROID_SUPPORT_VERSION": "26.+"
            },
            "springday-shealth": {}
        }
    }
}

please give some advice?

Thank you

**Comment by diegozuber** [comment]
@ambrosiajun see #116 

Try downgrading your @ionic-native plugins. Worked for me. Had the same error with v4.11.0

**Comment by Fuiste** [comment]
This doesn't look to be an issue with `cordova-plugin-ionic`, but rather the build process on Ionic's backend.  I'd try @diegozuber's suggestion first, and if that doesn't help [contact support](https://ionicframework.com/support)
