### ISSUE TITLE
Blank Screen on iOS & Android

### ISSUE THREAD

**Issue by diegozuber** [ionic-team/cordova-plugin-ionic#118]
I'm creating a new issue, because I think I found another problem that causes a blank screen on both platforms. 

I commited a new version to Ionic Deploy. This new Version had a new provider .ts file. After I assigned it to my Live Deploy Channel, all devices made the updates and it caused a white screen on all of them. After I removed that new .ts file from my project and recommited everything, all works again.

Hope you have enough to reproduce that.

Console Error after the redirect:
![bildschirmfoto 2018-08-10 um 11 55 03 am](https://user-images.githubusercontent.com/21689209/43952107-37acfee2-9c95-11e8-925f-d9f6598d8231.png)

EDIT: Maybe this #116 is somehow related to that problem?

**Comment by groeigids** [comment]
I also had the same sort of issue. In my case initially the app is starting up regular with a splashscreen 
for about 3 seconds and then the app is ready for the user to start.

After an update however the app takes much longer to start.

I found out that if there has been an update and dowloaded the most recenet version, the app starts with the initial 
snapshot. Then if it sees if there is a more current version, it will change to more cuurent version.
So locally it has two versions or snapshots. This change to the more recent snapshot takes about 10 to 12 seconds in our case.  Unfortunately this is for us to much time to take this feature into production.

**Comment by flyingwip** [comment]
I also had the same sort of issue. In my case initially the app is starting up regular with a splashsreen 
for about 3 seconds and then the app is ready for the user to start.

After an update however the app takes much longer to start.

I found out that if there has been an update and dowloaded the most recenet version, the app starts with the initial 
snapshot. Then if it sees if there is a more current version, it will change to more cuurent version.
So locally it has two versions or snapshots. This change to the more recent snapshot takes about 10 to 12 seconds in our case.  Unfortunately this is for us to much time to take this feature into production.

Maybe this info will help you

**Comment by ambrosiajun** [comment]
i have same error here too.

**Comment by RafaelSNascimento** [comment]
i have the same error here, somebody found a solution for this?

**Comment by nphyatt** [comment]
Myself and some other team members have been on vacation for the last couple weeks so we've been a little short on resources...going to try looking into this issue today.

**Comment by diegozuber** [comment]
@nphyatt Thanks, looks like it is working now. I will do some further testing.
