### ISSUE TITLE
Possible bug in IonicDeploy.m ? 

### ISSUE THREAD

**Issue by ransalman** [ionic-team/cordova-plugin-ionic#12]
Every app in iOS is stuck in splash screen and getting this error in xCode : 

2017-10-03 12:39:39.327033+0300 Appname[18366:5519289] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'
*** First throw call stack:
(0x1849d3d38 0x183ee8528 0x1849d3c80 0x185316720 0x18532deac 0x1046f0e20 0x10560949c 0x10560945c 0x105618110 0x10560c9a4 0x105619104 0x105620100 0x1845fefe0 0x1845fec30)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Tested in a few apps, even new apps created just for this test, I'm not the only one experiencing this error, see https://forum.ionicframework.com/t/nsinvalidargumentexception-on-ios/105283/5

any help appreciated..

**Comment by Fuiste** [comment]
I'm looking into this at the moment, and will make sure it's not happening in version 2.0.0 when it comes out within a week.

Check out the progress here https://github.com/ionic-team/cordova-plugin-ionic/pull/13

**Comment by Fuiste** [comment]
This should be fixed in version 2.0.0, let me know if it comes up again!
