### ISSUE TITLE
Blank Screen after Update 

### ISSUE THREAD

**Issue by RafaelSNascimento** [ionic-team/cordova-plugin-ionic#121]
After the update, the app is falling on a white screen, on account of the errors in the console. I don't know what's going on, I've wasted all day on this.

![capturar](https://user-images.githubusercontent.com/21286417/44165417-10fc1400-a09f-11e8-85e1-6643687344ee.PNG)

PackageJSON:
{
  ....
  },
  "dependencies": {
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/barcode-scanner": "^4.5.3",
    "@ionic-native/camera": "^4.5.3",
    "@ionic-native/core": "^4.4.0",
    "@ionic-native/geolocation": "^4.5.3",
    "@ionic-native/screen-orientation": "^4.5.3",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/pro": "^2.0.3",
    "@ionic/storage": "2.1.3",
    "angularfire2": "^5.0.0-rc.4",
    "clear": "^0.1.0",
    "cordova-android": "6.3.0",
    "cordova-ios": "4.5.4",
    "cordova-plugin-camera": "^4.0.1",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic": "^5.0.5",
    "cordova-plugin-ionic-webview": "^2.0.3",
    "cordova-plugin-screen-orientation": "^3.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-swift-support": "^3.1.1",
    "cordova-plugin-whitelist": "^1.3.1",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "^4.8.0",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "lodash": "^4.17.10",
    "phonegap-plugin-barcodescanner": "^7.0.2",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.11",
    "typescript": "2.4.2"
  },
  "description": "Upay App Project",
  "cordova": {
    "plugins": {
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-camera": {},
      "phonegap-plugin-barcodescanner": {
        "CAMERA_USAGE_DESCRIPTION": "Barcode Scanner"
      },
      "cordova-plugin-screen-orientation": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "Localização"
      },
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic": {
        "APP_ID": "xxxxxxxxxx",
        "CHANNEL_NAME": "Master",
        "UPDATE_METHOD": "auto",
        "WARN_DEBUG": "true",
        "UPDATE_API": "https://api.ionicjs.com",
        "MAX_STORE": "2",
        "MIN_BACKGROUND_DURATION": "30"
      }
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}

**Comment by vigege** [comment]
I have a same error.... :(

**Comment by RafaelSNascimento** [comment]
i will test it, Thanks!!!!!

**Comment by RafaelSNascimento** [comment]
Alright, now everything are working like a charm

**Comment by mikeciavHB** [comment]
5.0.9 fixed my issue as well
