### ISSUE TITLE
Offline Mode or Not connected to the internet

### ISSUE THREAD

**Issue by RafaelSNascimento** [ionic-team/cordova-plugin-ionic#125]
I can not run the app offline, the app is in the SplashScreen of the Downloader for unlimited time. When I'm debugging the device in Chrome, in Chrome the SplashScreen nn pops up, but on the phone is still with SplashScreen, so ignore the SccreenShoot where the app seems to be running normally.
![capturar1](https://user-images.githubusercontent.com/21286417/44286367-3b84d300-a23f-11e8-8c87-f964aa8a3f85.PNG)

Package JSON:
{
  "name": "upay",
  "version": "1.0.2",
  "author": "Upay App",
  "homepage": "",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build --prod",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/barcode-scanner": "^4.5.3",
    "@ionic-native/camera": "^4.5.3",
    "@ionic-native/core": "^4.4.0",
    "@ionic-native/diagnostic": "^4.12.0",
    "@ionic-native/geolocation": "^4.5.3",
    "@ionic-native/screen-orientation": "^4.5.3",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/pro": "^2.0.3",
    "@ionic/storage": "2.1.3",
    "angularfire2": "^5.0.0-rc.4",
    "clear": "^0.1.0",
    "cordova-android": "6.3.0",
    "cordova-ios": "4.5.4",
    "cordova-plugin-camera": "^4.0.1",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic": "^5.0.9",
    "cordova-plugin-ionic-webview": "^2.0.3",
    "cordova-plugin-screen-orientation": "^3.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-swift-support": "^3.1.1",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova.plugins.diagnostic": "^4.0.8",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "^4.8.0",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "lodash": "^4.17.10",
    "phonegap-plugin-barcodescanner": "^7.0.2",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.11",
    "typescript": "2.4.2"
  },
  "description": "Upay App Project",
  "cordova": {
    "plugins": {
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-camera": {},
      "phonegap-plugin-barcodescanner": {
        "CAMERA_USAGE_DESCRIPTION": "Barcode Scanner"
      },
      "cordova-plugin-screen-orientation": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "Localização"
      },
      "cordova-plugin-ionic": {
        "APP_ID": "xxxxxxxxxxx",
        "CHANNEL_NAME": "Production",
        "UPDATE_METHOD": "auto",
        "WARN_DEBUG": "true",
        "UPDATE_API": "https://api.ionicjs.com",
        "MAX_STORE": "2",
        "MIN_BACKGROUND_DURATION": "30"
      },
      "cordova-plugin-ionic-webview": {},
      "cordova.plugins.diagnostic": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}

**Comment by nphyatt** [comment]
@RafaelSNascimento thanks for the report! 

Looks like this was just a miss on our part. I just cut a pre-release that I was able to verify fixes the issue on iOS 100% and at least partially fixes on Android. I only have an emulator on Android and `navigator.onLine` was always returning `true` for me but the try/catch was at least loading the app after the request timed out (~30 seconds) which isn't ideal because you don't want the splash screen showing that long for no reason. However I suspect it works on a real device and maybe even on another emulator (I have VMware and docker installed which I saw could cause `navigator.onLine` to always return true. 

Anyway before I cut an actual release I wanted someone else to test and verify. You can install the fix using the `next` tag

```bash
cordova plugin add cordova-plugin-ionic@next
```

Let me know if you get a chance to try and if it solves the issue.

**Comment by nphyatt** [comment]
I was able to timeout the request so that after a maximum of 5 seconds it will consider itself offline and hide the splash screen in case the `navigator.onLine` give a false positive. With that fix I felt confident enough to release `5.0.10` which should fix your issue.

**Comment by RafaelSNascimento** [comment]
Now, it works, many thanks bro \o/

**Comment by RafaelSNascimento** [comment]
When the app is online, SplashScreen is staying forever because the downloader is not being called.
![sem titulo](https://user-images.githubusercontent.com/21286417/44299072-792c3f00-a2c5-11e8-9c84-c56bbdd1a79d.png)
Android: Galaxy A7, Version 7.0
I will downgrade it for 5.0.9

**Comment by RafaelSNascimento** [comment]
Cordova-Plugin-Ionic on my Android never waits 30 seconds to start downloading files, on my IOS X it starts to download immediately.
i set "MIN_BACKGROUND_DURATION" to 1 and 0, and nothing happens

**Comment by nphyatt** [comment]
@RafaelSNascimento `MIN_BACKGROUND_DURATION` is used to determine how long the app needs to be in the background for the plugin to consider it closed. If you open the app from a fully closed state it will check for and download any available updates on open. If you simply put the app in the background for at least the duration specified, 30 seconds by default, then the plugin will also check for and download an update on resume.

This is different from previous versions of the plugin which only checked for updates when the app was fully closed and then opened and now allows for updates if the app has been in the background for some length of time.

**Comment by nphyatt** [comment]
I'm going to close this issue as it seems to have been solved but feel free to open a new on if you're having a different issue.
