### ISSUE TITLE
Crash when downloading after upgrade to latest version

### ISSUE THREAD

**Issue by pmenager** [ionic-team/cordova-plugin-ionic#132]
**Describe the bug**
App crash when downloading the update since plugin version upgrade

**To Reproduce**
With manual management of the update process (using the API with UPDATE_METHOD="none")
1. Trigger Pro.deploy.download()
2. App is downloading, when logging the advancement, the download % increments until around ! 16%
3. App crash
4. In adb logcat we have the following crash log:

> 08-29 10:42:37.947 24168 24232 E chromium: [ERROR:aw_browser_terminator.cc(150)] Renderer process (24206) crash detected (code 5).
> 08-29 10:42:37.950 24168 24168 F chromium: [FATAL:aw_browser_terminator.cc(79)] Render process (24206)'s crash wasn't handled by all associated  webviews, triggering application crash.
> 08-29 10:42:37.951 24168 24168 F libc    : Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x7d137ad8f8 in tid 24168 (s.mobile.hauler), pid 24168 (s.mobile.hauler)

**Expected behavior**
To have the deploy process go through

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.6
 - Browser chrome
 - Version 68

**Smartphone (please complete the following information):**
 - Device: Google Pixel, OnePlus 5
 - OS: Android 9, Android 8.1.0

**Additional context**
We are using Ionic deploy since the begining without any issue. This issue appears after upgrading libs:
"cordova-plugin-ionic-webview": "^2.1.0"
"cordova-plugin-ionic": "^5.1.2"

With cordova-android: 7.1.1

Made a try with iOS and it seems to give inconsistant result, it go through once but takes a long time (several minutes on a wifi).

**Comment by pmenager** [comment]
Actually behaviour is inconsistant, sometimes the app crash as described sometimes it goes stuck.

**Comment by nphyatt** [comment]
@pmenager I think you may have been experiencing #131 we've release `5.1.3` of `cordova-plugin-ionic` which should address this. If you'd like to try upgrading and let us know if you're still experiencing issues that'd be great! thanks!

**Comment by pmenager** [comment]
Everything works as expected with `5.1.3, thanks @nphyatt!
