### ISSUE TITLE
Now IonicCordova.deploy.check does nothing

### ISSUE THREAD

**Issue by chrisdelambert** [ionic-team/cordova-plugin-ionic#14]
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v8.1.4
    npm               : 5.1.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : pro

I have updated to v2.0.0 of this plugin. When I call IonicCordova.deploy.check() nothing happens. No console log or anything.

I have this problem in a brand new project and an existing one.

Also, I get an error:

![img_0484](https://user-images.githubusercontent.com/19525279/31591965-4411bd3e-b281-11e7-8f0c-9055ac5c29aa.PNG)

**Comment by media4learning** [comment]
So after reading the changelog - there is a breaking change. When version 2.0.0 gives you the above error, you need to take the appId and channel params out of each function. The docs are not updated yet but I assume they will be soon.

**Comment by Fuiste** [comment]
Hey @chrisdelambert, it looks like @media4learning is correct here.  The function signatures changes in 2.0.0, and while I updated the docs and submitted the new definitions to `ionic-native`, it's possible they haven't been launched yet.  At the moment, you can use the README in this repo, but I'll make sure everything is up to date today.

Sorry for the inconvenience there.
