### ISSUE TITLE
Splash Screen (with autoHide off) overlaps with HTML for a second since v5.0.5

### ISSUE THREAD

**Issue by BorntraegerMarc** [ionic-team/cordova-plugin-ionic#151]
**cordova plugin ls output:**
```
com-sarriaroman-photoviewer 1.1.18 "PhotoViewer"
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-advanced-http 2.0.1 "Advanced HTTP plugin"
cordova-plugin-aes256-encryption 1.1.0 "AES256"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.0.1 "File Chooser"
cordova-plugin-filepath 1.4.2 "cordova-plugin-filepath"
cordova-plugin-filepicker 1.1.5 "File Picker"
cordova-plugin-ionic 5.0.5 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
komed-cordova-call 1.1.6 "CordovaCall"
komed-cordova-plugin-ionic-keyboard 2.1.2 "komed-cordova-plugin-ionic-keyboard"
komed-cordova-plugin-twiliovoice 2.5.0 "TwilioVoice"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

**ionic info output:**
```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/Users/borntsch/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.0.5, cordova-plugin-ionic-webview 2.1.4, (and 26 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.11.4 (/Users/borntsch/.nvm/versions/node/v8.11.4/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255
```

**Describe the bug**
Since upgrading this plugin to version 5.0.5 the splash screen overlaps with the HTML DOM for a split second, before the splash screen gets manually hidden. See Screen Recording nr. 1 for reference how it looks.

I also verified the same bug with version `5.1.6` and `5.2.4`.

**To Reproduce**
1. Add the following code in your `app.component.ts` file in the constructor:
```js
this.platform.ready().then((readySource: string) => {
  this.splashScreen.hide();
});
```
2. Add the following config in your `config.xml`:
```
<preference name="AutoHideSplashScreen" value="false" />
<preference name="SplashScreenDelay" value="0" />
<preference name="SplashMaintainAspectRatio" value="true" />
<preference name="FadeSplashScreenDuration" value="50" />
<preference name="SplashShowOnlyFirstTime" value="false" />
<preference name="SplashScreen" value="screen" />
```
3. Re-build the app (with deleting `plugins` folder) and start it.
4. See behaviour

**Expected behavior**
The app should behave like in the Screen recording nr. 2: The splash screen gets hidden without overlapping over the HTML.

**Screenshots**
Screen recording nr. 1 `cordova-plugin-ionic@5.0.5` with `cordova-plugin-ionic-webview@2.1.4`:

![screenrecording_09-19-2018 14-51-25 1](https://user-images.githubusercontent.com/7549295/45757032-b9fbd880-bc22-11e8-81e8-634584457248.gif)

Screen recording nr. 2 `cordova-plugin-ionic@4.1.7` with `cordova-plugin-ionic-webview@2.1.4`:

![screenrecording_09-19-2018 14-26-25](https://user-images.githubusercontent.com/7549295/45756788-0bf02e80-bc22-11e8-9047-6f0a9df21016.gif)

**Additional context**
I also noticed that `SplashScreenDelay` seems to have no effect if the splash screen is configured to `autoHide = true`. But couldn't verify it yet. I might create another bug later if it's really the case.

In the `config.xml` I have set `<preference name="DisableDeploy" value="true" />`

Funily: When using the version `5.0.0` then the plugin behaves correctly (like Screen Recording nr. 2) but only on the first app start. Every 2nd app start results in the splash screen not disappearing ever.

**Comment by jcesarmobile** [comment]
I wasn't able to reproduce in my project, can you provide a minimal sample project? or if you have it in pro, the app id

**Comment by BorntraegerMarc** [comment]
Thanks for the follow up @jcesarmobile

My app ID is 82c77fc1

I also wasn't able to reproduce the bug in a ionic starter project. So maybe the bug comes with the size of the project?

**Comment by jcesarmobile** [comment]
The problem is your splash images have transparent background. 

It's not really a bug on cordova-plugin-ionic as I can reproduce even without it installed.
If you add this preference `<preference name="AutoHideSplashScreen" value="false" />` and remove your call to hide on device ready, the splash will remain over your app and you'll be able to see it but not interact with it.

I also could randomly reproduce with 4.x.x of the plugin by launching multiple times, but this is more noticeable on 5.x.x because it now has less native code and more js code, and while the js code is checking for updates it shows the splash. It's just a brief 1/2 second, but enough for you to see this effect.

So I can think of 2 options:
1. Add some color to your splash images background
2. Report the issue on cordova-plugin-splashscreen to add a background color preference or something to show some solid color behind the splash image.
