### ISSUE TITLE
The version is not updated on Android (it seems) (update never triggered)

### ISSUE THREAD

**Issue by mparpaillon** [ionic-team/cordova-plugin-ionic#16]
Hi,

I followed the online tutorial and tried to apply it but it didn't work.
So I used `adb logcat` to see what was happening. And I saw this: 

```
IONIC.DEPLOY.INIT: VChecks
IONIC.DEPLOY.INIT: Version Label 1: 4.4.16:1508248680742:NO_DEPLOY_AVAILABLE
IONIC.DEPLOY.INIT: Version Label 2: 4.4.16:1508248680742:NO_DEPLOY_AVAILABLE
```

In my config.xml, the version is 4.4.17 though. Is it the right place to increment the version in order to trigger the update ? Or am I missing something ? How does this check works ? 

I took a look at the Android code (which I don't really understand tbh).
Apparently there's this function to get the UUID:
https://github.com/ionic-team/cordova-plugin-ionic/blob/master/src/android/IonicDeploy.java#L184
```java
private String getUUID(String defaultUUID) {
  return this.prefs.getString("uuid", defaultUUID);
}
```

So I looked for the `this.prefs` bit and apparently it's initiated from a `getPreferences()` function:
https://github.com/ionic-team/cordova-plugin-ionic/blob/master/src/android/IonicDeploy.java#L705
```java
private SharedPreferences getPreferences() {
  // Request shared preferences for this app id
  SharedPreferences prefs = this.myContext.getSharedPreferences("com.ionic.deploy.preferences", Context.MODE_PRIVATE);
  return prefs;
}
```

... aaaaand that's it. I don't know how to go further.

So... where should I change my app version to trigger the update ?

Thanks a lot

**Comment by Fuiste** [comment]
From those first few logs, it appears that you do not have a deploy downloaded on your device when the app starts.  This tells me that you're either running the plugin in manual mode or there is no update available on initial check.  

First, are you able to see that you're getting a response from the deploy server?  You can see this information logged in `logcat` when you call `check`.

I'd also make sure you're setting the correct `native versioning` on your deploys, which you can see in the modal on the ionic dashboard when deploying an update.

**Comment by mparpaillon** [comment]
Hi @Fuiste Thank you for your answer.

The plugin is installed like this (with the right "app_id" and "channel_name" of course)
```
cordova plugin add cordova-plugin-ionic --save --variable APP_ID="YOUR_APP_ID" --variable CHANNEL_NAME="YOUR_CHANNEL_NAME" --variable UPDATE_METHOD="background"
```

So not manual mode, right ? Also this works on iOS so the plugin installation is OK I guess.

The native versionning is OK I think but I'll double check this.

I'm gonna give it a try and give you the `logcat` logs

**Comment by mparpaillon** [comment]
It seems to work now for some reason (I just reinstalled the plugin). I have a question though, if I want a dev build when deploying to "master" and a production build when I deploy to "production" what should I do ?

**Comment by Fuiste** [comment]
Update on this issue, I've just released version 2.0.2 of the plugin, which may be related.

Can you try this version as well and verify that the problem is still occurring?

**Comment by Fuiste** [comment]
@mparpaillon Glad you got the problem sorted!

As to your question, I'm not sure what you're requesting, as a dev vs. production build is something that you would decide at build time and isn't tied to the deploy channel you're using.  That said, this seems like a problem that someone could help you out with in the forums (https://forum.ionicframework.com/).

**Comment by mparpaillon** [comment]
@Fuiste When I push to a channel it triggers the build of the project right ? You can see this in the build logs. So right now, it seems to build the app in dev mode. Or am I missing something ?
