### ISSUE TITLE
Fetch is unavailable so cordova-plugin-ionic has been disabled.

### ISSUE THREAD

**Issue by bellalMohamed** [ionic-team/cordova-plugin-ionic#165]
**cordova plugin ls output:**
```
Fetch is unavailable so cordova-plugin-ionic has been disabled. common.js:1016
```

**Describe the bug**
Simply Android App Is not able to fetch the update from ionic pro

**To Reproduce**
1. Install ionic pro plugin 
2.build the app

**Expected behavior**
Expected the app to load the update from the ionic pro servers

**Comment by jcesarmobile** [comment]
If fetch is not available some features are disabled. If you are in android 5 or 6 make sure you have an updated system webview. If you are in Android 7 or newer make sure you have latest chrome. All those should support fetch.
If you are in android 4.4 some features won’t work as it doesn’t support fetch

**Comment by bellalMohamed** [comment]
I Installed https://github.com/github/fetch plugin and everything worked fine

**Comment by Colombo97** [comment]
Im facing the samme problem

**Comment by Colombo97** [comment]
> I Installed https://github.com/github/fetch plugin and everything worked fine

How do you solve this issue?

**Comment by bellalMohamed** [comment]
@Colombo97 
Just run 
`npm install whatwg-fetch --save`

**Comment by Colombo97** [comment]
I did this and the problem persists.
