### ISSUE TITLE
Ionic run conflicts with ionic pro

### ISSUE THREAD

**Issue by sfaizanh** [ionic-team/cordova-plugin-ionic#17]
If i run the app from terminal `ionic cordova run ios -l -c` then Ionic Pro is conflicting with ionic Pro, 
ex. if app is reloaded again by saving a file then old app appears from ionic-pro.
```
cli packages:
    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:
    cordova (Cordova CLI) : 7.0.1 

local packages:
    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.6 
    Node       : v6.11.2
    npm        : 5.4.2 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Misc:
    backend : pro
```

Another question: If i implement ionic pro monitoring how to get JS error in browser on `ionic serve`
```
export class MyErrorHandler implements ErrorHandler {
	handleError(err: any): void {
		IonicPro.monitoring.handleNewError(err);
		throw new Error(err);
	}
}
```
is `throw new Error(err)` is correct?

**Comment by mlynch** [comment]
What do you mean "conflicting?"

And for the code snippet, try `throw err;` instead

**Comment by sfaizanh** [comment]
When run app on device from ‘ionic cordova run ios -l -c’, so it starts the app successfully after 2 or 3 minutes when i kill the app from device then open the app, Ionic cordova plugin downloads the app from Ionic pro (from master branch). I have to delete the app from mobile then run again.

**Comment by fierysolid** [comment]
Basically if you have auto updates on and you are trying to develop the app, it will snag the latest deployment and live reload stops working since its running a deploy version and not the dev version you built.

**Comment by sfaizanh** [comment]
Closing it's may be fixed now. Alert dialog popup, do you want to **Update** or **Ignore**
