### ISSUE TITLE
Can't get updates

### ISSUE THREAD

**Issue by shlomiLan** [ionic-team/cordova-plugin-ionic#174]
**cordova plugin ls output:**
```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic 5.2.5 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**ionic info output:**
```
Ionic:

   ionic (Ionic CLI)  : 4.2.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic 5.2.5, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 6 other plugins)

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
```

**Describe the bug**
When I open the app I didn't see any change? is there a way to debug this issue? to see if the event is firing? Also do I need to have a paid account in order to use this feature or a free account in enough?

**To Reproduce**
1. Run `cordova plugin add cordova-plugin-ionic --save --variable APP_ID="APP_ID" --variable CHANNEL_NAME="Production" --variable UPDATE_METHOD="auto"`
2. Rebuild the android app with `ionic cordova build android --prod --release`
3. Make change in `.ts` file
4. Push changes to git and see a new build in `Ionic Dashboard`
5. Assign the new build to the `Production` channel.
6. Kill the app on the phone and reopen it
7. No updates to the `.ts` file.

**Expected behavior**
New version when I lunch the app.

**Comment by jcesarmobile** [comment]
You don't need a paid account.
Changes are not done on your .ts file, the app will download the new code and apply it.
If you open chrome device inspector you should be able to see some of the plugin logs about downloading the code.

**Comment by shlomiLan** [comment]
After running:
`ionic cordova run android --device --prod`
while the device is connected (with USB) and inspecting with Chrome, I see the following messages in the console:
```
Ionic Pro initializing (app id: a9f030da)
vendor.js:1 Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
x @ vendor.js:1
vendor.js:1 Native: tried calling SplashScreen.hide, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
x @ vendor.js:1
(index):1 Failed to decode downloaded font: http://localhost:8080/assets/fonts/roboto-regular.woff2
(index):1 Failed to decode downloaded font: http://localhost:8080/assets/fonts/roboto-regular.woff
(index):1 Failed to decode downloaded font: http://localhost:8080/assets/fonts/roboto-regular.ttf
vendor.js:1 the cordova-plugin-ionic plugin is not installed. Install it for better device information for runtime errors.
```

**Comment by jcesarmobile** [comment]
Do you have cordova.js linked in your index.html?
What do you get if you run cordova plugins command?

**Comment by shlomiLan** [comment]
Uncommenting `cordova.js` in `index.html` did the trick. Thanks.
