### ISSUE TITLE
Plugin renders ionic cordova run browser useless

### ISSUE THREAD

**Issue by philonor** [ionic-team/cordova-plugin-ionic#176]
**cordova plugin ls output:**
```
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.2.6 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
```

**ionic info output:**
```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.7

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.6, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 17 other plugins)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the bug**
When running `ionic cordova run browser`, app hangs on splashscreen due to error `Error: exec proxy not found for :: IonicCordovaCommon :: getPreferences`.

**To Reproduce**
1. Start with empty project
2. Run `ionic cordova plugin add cordova-plugin-ionic --save --variable APP_ID="abcd1234" --variable CHANNEL_NAME="Master" --variable UPDATE_METHOD="background"`
3. Run `ionic cordova run browser`
4. Error occurs in console
```
Error: exec proxy not found for :: IonicCordovaCommon :: getPreferences
```

**Expected behavior**
This plugin only supports iOS and Android, but shouldn't completely render the browser platform useless. A Browser stub that just does nothing, e.g., would be completely okay.

**Screenshots**
![image](https://user-images.githubusercontent.com/5816039/47798230-43c1ba00-dd28-11e8-9762-ded8fd49df2d.png)
![image](https://user-images.githubusercontent.com/5816039/47798289-618f1f00-dd28-11e8-8c4a-aab79757eec9.png)

**Additional context**

**Comment by wilkovanhoek** [comment]
I can confirm this. I am having the same issue with the new version 5.2.7. Must have happened between version 5.2.5 and 5.2.7. Version 5.2.5 works flawlessly for me. Unfortunately, this renders the plugin useless for people who want to use mobile and browser.

**Comment by cgbrucezjy** [comment]
> I can confirm this. I am having the same issue with the new version 5.2.7. Must have happened between version 5.2.5 and 5.2.7. Version 5.2.5 works flawlessly for me. Unfortunately, this renders the plugin useless for people who want to use mobile and browser.

You are right, downgrading to 5.2.5 fixed the issue for me, anyone know what's happening to the new version? i'm using ionic 3, could that be an issue?

**Comment by jcesarmobile** [comment]
I've tested 5.2.5 and I see the exact same error displayed. 
But despite the error it's working fine on my app on 5.2.5, 5.2.7 and 5.2.8. 

You have `<preference name="AutoHideSplashScreen" value="false" />` in the config.xml, right? 
If so, as workaround you can remove the preference (remove it, don't set it to true), it's being added to iOS and Android by the plugin already, and having the preference is making it to not disappear. 

But keeping the issue open to make the plugin compatible with browser.

**Comment by cgbrucezjy** [comment]
I'm still seeing the issue as well, what I did is just remove ionic-cordova-plugin for browser only, since it's not used anywhere in browser

**Comment by jcesarmobile** [comment]
Did you read my comment?
