### ISSUE TITLE
Fetch is unavailable so cordova-plugin-ionic has been disabled.

### ISSUE THREAD

**Issue by Colombo97** [ionic-team/cordova-plugin-ionic#177]
**cordova plugin ls output:**
```
cordova-background-geolocation 2.13.2 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.2.6 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
```

**ionic info output:**
```

   ionic (Ionic CLI)  : 4.2.1 (C:\Users\Colombo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic 5.2.6, cordova-plugin-ionic-webview 2.2.0, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Colombo\appData\local\android\sdk)
   NodeJS            : v8.11.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10


```

**Describe the bug**
chrome inspect showing "Fetch is unavailable so cordova-plugin-ionic has been disabled.".
I can not get updates in code

**To Reproduce**
1-ionic cordova run android
2-verify if app is opened
3-verify chrome inspect

**Expected behavior**
I hope you resolve the error regarding this message in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/26873614/47811462-37376480-dd1c-11e8-8263-887e0ad89fa7.png)
![image](https://user-images.githubusercontent.com/26873614/47810694-4fa67f80-dd1a-11e8-9057-d5781b848af0.png)
Fetch object pointing to node_modules of VSCode: :--s
![image](https://user-images.githubusercontent.com/26873614/47811134-6dc0af80-dd1b-11e8-9f5f-5cf976202538.png)

![image](https://user-images.githubusercontent.com/26873614/47810943-e5daa580-dd1a-11e8-9b7f-06c734c6f0d3.png)

**Additional context**
Im trying use this plugin to upload files to Ionic Pro
I saw the last issue about this problem, but I did not have success

**Comment by jcesarmobile** [comment]
Read my comment on https://github.com/ionic-team/cordova-plugin-ionic/issues/165

If your device doesn't have fetch some things won't work.
If it's a real device, update the system webview or chrome (depends on the Android version)
If it's an emulator, try using one with Android 6 or newer (or try updating the webview if possible)

**Comment by Colombo97** [comment]
Thank you, i've tested on mobile and worked. On emulator, how can i update webview??
