### ISSUE TITLE
After closing app switches back to an older version.

### ISSUE THREAD

**Issue by henritoivar** [ionic-team/cordova-plugin-ionic#18]
The updates don't seem to persist.

Also i cannot rollback to any previous commits. 

Tested on iOS simulator.

I also had some unexpected behavior on Android. Is this plugin still in beta?

**Comment by Fuiste** [comment]
Are you using the latest version of the plugin?

If so, can you list the steps to get an update failing to persist?  I ask because I can't reproduce on plugin 2.0.0 on an iOS device.

It's worth noting that if you're on a debug builds of your app, you'll be asked before any update is loaded.

**Comment by henritoivar** [comment]
Yes, using latest. The issue happened with a debug build on the simulator. Every time i open it again, it asks to download the update again. Doesn't seem to be happening on a real device.

Also i discovered that on android it was automatically updating to the latest play store build as i was using the same build credentials. So this got me confused. Everything seems to be OK now on Android.

**Comment by Fuiste** [comment]
If you're in a debug build, the plugin will ask you before _any_ redirection takes place.  This is so that you can develop on the bundled version of your app without accidentally applying a deploy.  

The dialog asking if you would like to redirect will not appear on production builds.
