### ISSUE TITLE
Stuck at Splashscreen - Debug mode

### ISSUE THREAD

**Issue by mgrbose** [ionic-team/cordova-plugin-ionic#19]
I am using this latest Deploy pro plugin. I am testing on Android device using Debug mode. I can see the Debug dialog (I think with "Ignore" "Update") just for about a second and then this dialog seem to go to background and is stuck at Splashscreen. 

I can see the changes downloading and extracting on logcat. But the issue seems to be that the Debug confirmation ("Ignore" "Update") just comes for a second and disappears, so stuck at Splashscreen. Thanks a lot for looking into this. 

ionic info
cli packages: (/usr/local/lib/node_modules)
ionic/cli-utils : 1.15.1
ionic (Ionic CLI) : 3.15.1

global packages:
cordova (Cordova CLI) : 7.0.1 

local packages:
ionic/app-scripts : 3.0.0
Cordova Platforms  : android 6.2.3
Ionic Framework    : ionic-angular 3.7.1

System:
ios-deploy : 1.9.0 
Node       : v8.3.0
npm        : 5.3.0 
OS         : macOS Sierra
Xcode      : Xcode 9.0 Build version 9A235 

Misc:
backend : pro

**Comment by Fuiste** [comment]
I just released version 2.0.2 of the plugin to address this issue,  let me know if this solves it for you.

Cheers!

**Comment by mgrbose** [comment]
Thank you.. Its working now.
