### ISSUE TITLE
Invalid definition types

### ISSUE THREAD

**Issue by leandrogehlen** [ionic-team/cordova-plugin-ionic#190]
In @ionic/pro the file definitions.d.ts has the follow declaration:

```typescript
export interface App {
    ...
    getPlugin(): Promise<Window['IonicCordova']>;
```

but the `index.d.ts` has : 

```typescript
declare class Pro implements App {
    ...
    getPlugin(): Promise<Window['IonicCordova'] | undefined>;
```

when is used the property `"strictNullChecks": true`  in `tsconfig.json` the exception is raised.

**Comment by jcesarmobile** [comment]
Fixed in @ionic/pro 2.0.4
