### ISSUE TITLE
Android: App doesn't load after update (if you close and reopen)

### ISSUE THREAD

**Issue by vontangen** [ionic-team/cordova-plugin-ionic#193]
**cordova plugin ls output:**
```
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.2.7 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-keychain 3.0.1 "KeyChain Plugin for Cordova iOS"
cordova-plugin-launchscreen-storyboard 1.0.1 "LaunchScreenStoryboard"
cordova-plugin-multidex 0.1.2 "Cordova Multi Dex"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
es6-promise-plugin 4.2.2 "Promise"
linea-pro-cdv 0.2.6 "LineaProCDV"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"
phonegap-plugin-local-notification 1.0.1 "phonegap-plugin-local-notification"
uk.co.workingedge.phonegap.plugin.istablet 1.2.0 "Is Tablet"
```

**ionic info output:**
```
Ionic:

   ionic (Ionic CLI) : 4.2.1
   Ionic Framework   : unknown
   @ionic/v1-toolkit : 1.0.10

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : cordova-plugin-ionic 5.2.7, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 24 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Jorgen\AppData\Local\Android\sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Describe the bug**
After doing a successful ionic deploy, the app will no longer load when you cold start it. The reason is that during bootstrapping, cordova-plugin-ionic attempts to construct a URL for the call Ionic.WebView.setServerBasePath. The URL uses cordova.file.dataDirectory, which is not set when the bootstrapping runs.
When I put a breakpoint on the line where the URL is constructed and immediately resume, the app loads fine.

The same app does not have this issue in iOS.

**Expected behavior**
App should load. Bootstrapping should not occur before cordova.file.dataDirectory has been set.

** Screenshots below **

![image](https://user-images.githubusercontent.com/8288633/49649981-194fd480-fa2b-11e8-8cd6-0cf1ca37ab51.png)

![image](https://user-images.githubusercontent.com/8288633/49649992-279df080-fa2b-11e8-81e5-5a30e44ab0cc.png)

**Comment by jcesarmobile** [comment]
Why did you close?

**Comment by vontangen** [comment]
The issue I had was caused by us having an empty cordova.js file in the www-folder to avoid a 404-error when we run the app directly in the browser. This has worked with previous versions, but I noticed the current version of ionic deploy copies it over to the device during deployment. Breaking the app on Android. As far as I can tell, this does not happen on iOS. 
This started happening after we upgraded to v5.x of cordova-plugin-ionic.

**Comment by jcesarmobile** [comment]
I have seen this a few times and I don’t have the empty cordova.js, so I don’t thing it’s related. But it doesn’t happen every time. Going to reopen to keep looking into it

**Comment by drahuks** [comment]
Hello,
I am facing the same issue. Running ionci cordova run -lc android gives me an error
`[app-scripts] [11:48:47]  console.log: Current: versionCode: 10006 versionName: 1.0.6
[app-scripts] [11:48:47]  console.log: update: versionCode: 10006 versionName: 1.0.6
[app-scripts] [11:48:47]  console.error: Unhandled Promise rejection: Failed to construct 'URL': Invalid URL ; Zone: <root> ; Task:
[app-scripts]             Promise.then ; Value: [object Object] TypeError: Failed to construct 'URL': Invalid URL at
[app-scripts]             IonicDeployImpl.<anonymous> (http://192.168.20.126:8100/plugins/cordova-plugin-ionic/dist/common.js:515:39)
[app-scripts]             at step (http://192.168.20.126:8100/plugins/cordova-plugin-ionic/dist/common.js:37:23) at Object.next
[app-scripts]             (http://192.168.20.126:8100/plugins/cordova-plugin-ionic/dist/common.js:18:53) at fulfilled
[app-scripts]             (http://192.168.20.126:8100/plugins/cordova-plugin-ionic/dist/common.js:9:58) at t.invoke
[app-scripts]             (http://192.168.20.126:8100/build/polyfills.js:3:14976) at r.run
[app-scripts]             (http://192.168.20.126:8100/build/polyfills.js:3:10143) at
[app-scripts]             http://192.168.20.126:8100/build/polyfills.js:3:20242 at t.invokeTask
[app-scripts]             (http://192.168.20.126:8100/build/polyfills.js:3:15660) at r.runTask
[app-scripts]             (http://192.168.20.126:8100/build/polyfills.js:3:10834) at o
[app-scripts]             (http://192.168.20.126:8100/build/polyfills.js:3:7894)`

If I run using ionic cordova run android --prod, everythings is ok. More, if I then re-run with -lc, it works well!

My plugin list
`cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-ionic 5.2.7 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"`

ionic info

`Ionic:

   ionic (Ionic CLI)  : 4.5.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 7.1.4, ios 4.5.5, windows 6.0.1
   Cordova Plugins       : cordova-plugin-ionic 5.2.7, cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 2.3.1, (and 15 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\MobileIT\Android\android-sdk)
   NodeJS            : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10`
