### ISSUE TITLE
Deploy crashes with comment regex check

### ISSUE THREAD

**Issue by mlynch** [ionic-team/cordova-plugin-ionic#21]
There are some crash reports indicating Deploy is crashing checking for the cordova commented out regex inside of `doRedirect`:

![screen shot 2017-11-03 at 3 16 11 pm](https://user-images.githubusercontent.com/11214/32394088-f4873e24-c0a9-11e7-812a-078528cb265d.png)

Here's the stack trace provided by a Pro user:

![screen shot 2017-11-03 at 3 14 57 pm](https://user-images.githubusercontent.com/11214/32394061-d9a750f8-c0a9-11e7-9c64-ecad29c99262.png)

**Comment by timbru31** [comment]
This is still a relevant issue. Somehow the `*htmlData` variable is `nil` - there is no error handling for this case at all.
I'm still investigating why the `*htmlData` variable is nil.

**Comment by Fuiste** [comment]
After testing on plugin version 4.0.0 with multiple devices I am unable to reproduce this issue.  If you can reproduce, let me know and I'll reopen this.

**Comment by martinchamrad** [comment]
This is still happening in 4.1.6.
Not all users are affected but those who are, can't get past this crash.
![image](https://user-images.githubusercontent.com/1964575/41467133-9233baa2-70a5-11e8-9997-d8d76e3feddd.png)

**Comment by jasonrmartin** [comment]
We are having this issue with 2 users as well.

**Comment by jcesarmobile** [comment]
Considering that code is gone in 5.x.x, I would say yes
