### ISSUE TITLE
Cannot install cordova-plugin

### ISSUE THREAD

**Issue by Lucaszw** [ionic-team/cordova-plugin-ionic#211]
**cordova plugin ls output:**
```
npm ERR! code E404
npm ERR! 404 Not Found: @ionic/typedoc-plugin-markdown@^1.0.5

npm ERR! A complete log of this run can be found in:
```

**Attempted with yarn also:**

yarn install exited 1 in ...
An unexpected error occurred: 
[https://registry.yarnpkg.com/@ionic/typedoc-plugin-markdown](https://registry.yarnpkg.com/@ionic/typedoc-plugin-markdown): Not found.

**ionic info output:**
```
Ionic:

   ionic (Ionic CLI) : 4.12.0 
   Ionic Framework   : unknown
   @ionic/v1-toolkit : not installed

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : no whitelisted plugins (9 plugins total)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.3 
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001
```

**Describe the bug**
I have attempted to install ionic-cordova-plugin; but fails with the error above.

**To Reproduce**
1. Run ```ionic cordova plugin add cordova-plugin-ionic```

**Expected behavior**
Should install

**Comment by nphyatt** [comment]
@Lucaszw this should only be an issue on the `next` `5.4.0-0` tag which is a pre-release. pre-releases are not expected to be stable/bug free. please use the `latest` tag currently `5.3.0` to resolve the issue.
