### ISSUE TITLE
npm  WARN deprecated  @types/cordova-plugin-file-transfer@1.6.2

### ISSUE THREAD

**Issue by stagrlee** [ionic-team/cordova-plugin-ionic#212]
$ npm -i
npm WARN deprecated @types/cordova-plugin-file-transfer@1.6.2: This is a stub types definition for cordova-plugin-file-transfer (https://github.com/apache/cordova-plugin-file-transfer). cordova-plugin-file-transfer provides its own type definitions, so you don't need @types/cordova-plugin-file-transfer installed!

**Comment by jcesarmobile** [comment]
Closing as file-transfer was removed on 5.4.0
