### ISSUE TITLE
cordova-plugin-file dependency clobbers File

### ISSUE THREAD

**Issue by JetUni** [ionic-team/cordova-plugin-ionic#213]
**cordova plugin ls output:**
```
> cordova plugin ls

com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-android-support-gradle-release 2.1.0 "cordova-android-support-gradle-release"
cordova-clipboard 1.2.1 "Clipboard"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-ble-central 1.2.2 "BLE"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-fingerprint-aio 1.7.0 "FingerprintAllInOne"
cordova-plugin-flashlight 3.2.0 "Flashlight"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.3.0 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.4.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-secure-storage 3.0.2 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

**ionic info output:**
```
$ ionic info

Ionic:

   Ionic CLI                     : 5.0.0 (/Users/jarrett/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.1, (and 22 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (/Users/jarrett/sites/android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.15.3 (/Users/jarrett/.nvm/versions/node/v10.15.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Describe the bug**
The cordova-plugin-file dependency of this app clobbers the native web api File object. When trying to return a new file, nothing is in the correct place in the object.

**To Reproduce**
1. Create new array, i.e. `var a = new Uint8Array(4)`
2. Create new File, i.e. `var f = new File([a], "filename", { type: "image/jpeg" });
3. Inspect f
4. See error where name is the array and some other fields are null

**Expected behavior**
Perform the above steps in the console of a page that hasn't clobbered the native web api File to see what the object should look like. I expect a new file to be created using the native web api File. I hope that you can remove this dependency as its methods are ancient and it clobbers the global scope.

**Screenshots**
![image](https://user-images.githubusercontent.com/1317221/59791554-9dfb9500-928f-11e9-8893-5d22c21a7942.png)

**Additional context**
The screenshot above shows the getFileFromDataURI function which is supposed to return a File object using the native web api, but because the plugin has clobbered that, it returns a bad object as can be seen in the console.

**Comment by nphyatt** [comment]
👋 @JetUni I really want to get rid of this dependency as well...not only is this an issue but it has caused other issues as well...I'm looking in to what it would currently take to achieve this but of course we're very busy so I have no estimated timeline for this. Mostly this plugins uses it for a few things:
1) to  copy/move files around
2) it uses file transfer to speed up downloading of assets by doing both the download and the write to filesystem in the native layer and avoiding incurring the expensive cost of passing the file over the cordova bridge for doing something like using `fetch` and then writing to file

**Comment by JetUni** [comment]
If you could reply with a detailed overview of what needs to be done to remove this dependency, I could hopefully help fix at least part of it. I appreciate you looking into this!

**Comment by nphyatt** [comment]
@JetUni So I took the liberty of completely removing the `cordova-plugin-file` dependency as I was making some related changes and I published a prelease. If you want to test it's `5.4.0.1` or `cordova-plugin-ionic@next` let me know how it works for you. I'm having some others test too and if it looks good we'll release it at lates sometime early next week.

**Comment by jcesarmobile** [comment]
Closing as 5.4.0 was released without cordova-plugin-file dependency
