### ISSUE TITLE
Uncaught (in promise) String resource ID #0x0 (Android emulator)

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/cordova-plugin-ionic#223]
**cordova plugin ls output:**
```
-bash: cordova: command not found
```
Note: I don't use Cordova directly, I'm trying to do everything via Capacitor.

**ionic info output:**
```
Ionic:

   Ionic CLI                     : 5.2.7 (/Users/nunoarruda/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.803.0
   @angular-devkit/schematics    : 8.3.0
   @angular/cli                  : 8.3.0
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/Users/nunoarruda/.nvm/versions/node/v10.16.3/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Describe the bug**
Ionic app fails to load properly on an Android emulator (Pixel 2 API 24 - Android 7.0)

**To Reproduce**
1. `npx cap open android`
2. Run emulator
3. Open "Remote Devices" on Google Chrome
4. "Inspect" Android Emulator and see check "Console"

**Expected behavior**
Ionic app should load properly.

**Screenshots**
<img width="1440" alt="Screenshot 2019-09-02 at 12 01 08" src="https://user-images.githubusercontent.com/1189149/64107130-109dec00-cd7a-11e9-9cc4-3abc5673b7c7.png">

**Additional context**
Works fine on iOS. I do not own an Android device. Any ideas?

**Comment by jcesarmobile** [comment]
Probably related to https://github.com/ionic-team/capacitor/issues/1958
Should be fixed in next Capacitor release

**Comment by terranmarine** [comment]
For me this was fixed one I removed app incompatible cordova plugins.

**Comment by lucasamdasilva** [comment]
I really have a problem. Any discoveries? @nunoarruda
