### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED Cordova android

### ISSUE THREAD

**Issue by MurugananthamS** [ionic-team/cordova-plugin-ionic#225]
Failed to load resource: net::ERR_CONNECTION_REFUSED
**Describe the bug**
i have developing one android application using cordova ,i have facing the following issue while calling api,kindly help me out this issue  
   
       Failed to load resource: net::ERR_CONNECTION_REFUSED(http://ip address:8080)

var uName = $('#UserName_input').val();
    var pwd = $('#Password_input').val();
    console.log("GetLogin function CallED~~~~~~~~~~~~~");
    console.log("GetLogin InternetStatus ~~~~~~~~~~~~~" + InternetStatus);
    console.log("GetLogin function uNam~~~~~~~~~~~~~" + uName);
    console.log("GetLogin function pwd ~~~~~~~~~~~~~" + pwd);
    if (InternetStatus == 'Online') {
        if (uName != "" && pwd != "") {
            //SpinnerDialog.show("Loading", "Please Wait...", true);
            $(".modal").show();
            /*---------->*/
            // alert("call before AJAX------>");
            debugger
            $.ajax({
                    url: baseURL + checkLogin,
                    type: 'POST',

                    data: {
                        'userName': uName,
                        'password': pwd
                    },
                    // ~~~~~~~~~~~~~~~~~  Basic autherntication ~~~~~~~~~~~~~~~~~~~~~~~~
                    /* beforeSend: function(xhr) {
                         xhr.setRequestHeader("Authorization", "Basic " + btoa("crewMobieAppAdmin" + ":" + "!uT#61@c#"));
                     },*/
                    success: function(result)
                        //we got the response
                        {

**Comment by nphyatt** [comment]
This is not the right place for this question. This is the repo for the Ionic Deploy plugin. Also you seem to have copy pasted some Basic Auth credentials in your issue so you should probably change those credentials now.
