### ISSUE TITLE
No Updates are applied on iOS

### ISSUE THREAD

**Issue by iliraga** [ionic-team/cordova-plugin-ionic#229]
**cordova plugin ls output:**

```
cordova-background-geolocation 3.2.2 "BackgroundGeolocation"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 2.2.0 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 5.6.0 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-facebook4 6.2.0 "Facebook Connect"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-firebase-analytics 2.0.4 "FirebaseAnalyticsPlugin"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-intercom 7.1.1 "Intercom"
cordova-plugin-ionic 5.4.5 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 4.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-wfl-config 0.2.0 "cordova-plugin-wfl-config"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.0 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.3.1 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.6.0 "OneSignal Push Notifications"

```

And only the Ionic Plugin Part - extracted from above:

```
cordova-plugin-ionic 5.4.5 "cordova-plugin-ionic"
```

**ionic info output:**

```
Ionic:

   Ionic CLI          : 5.2.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.8
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.5, cordova-plugin-ionic-webview 4.1.2, (and 32 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (/Users/iliraga-hitouch/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm               : 6.11.2
   OS                : macOS Mojave
   Xcode             : Xcode 11.2 Build version 11B52

```

**Describe the bug**

After releasing our app we're facing an issue that Ionic Deploy does not load updates on iOS anymore. *But only on iOS*, on Android it works like charm.

**To Reproduce**

1. We open our app - sorry it's not available yet. I could give you TestFlight Access if really nessecary.

**Expected behavior**

It should fetch the latest version.

**Additional context**

**Logs***
Somehow I was able to extract this error logs:
```
ERROR: Unhandled Promise rejection: The string did not match the expected pattern. ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError: The string did not match the expected pattern. json@[native code]
ionic://localhost/plugins/cordova-plugin-ionic/dist/common.js:256:55
step@ionic://localhost/plugins/cordova-plugin-ionic/dist/common.js:35:27
fulfilled@ionic://localhost/plugins/cordova-plugin-ionic/dist/common.js:7:62
run@ionic://localhost/build/polyfills.js:3:10149
ionic://localhost/build/polyfills.js:3:20245
runTask@ionic://localhost/build/polyfills.js:3:10844
o@ionic://localhost/build/polyfills.js:3:7901
promiseReactionJob@[native code]
```

The Configuration of the Plugin is:

```
      "cordova-plugin-ionic": {
        "APP_ID": "99bdb622",
        "CHANNEL_NAME": "Production-v4.6.0",
        "UPDATE_METHOD": "auto",
        "UPDATE_API": "https://api.ionicjs.com",
        "MAX_STORE": "2",
        "MIN_BACKGROUND_DURATION": "30"
      },

```

Unfortunately it's quite urgent - the release is coming soon. We're talking here about an app served to around 120k Users.

**Comment by nphyatt** [comment]
what's the version number in iOS? You can find by looking in xcode.
![image](https://user-images.githubusercontent.com/6487450/68048556-ce782480-fcae-11e9-9adc-f4ddd809d3c5.png)

This must be a valid [semantic version](https://semver.org/).

**Comment by iliraga** [comment]
It is `4.6.0` - Build as well.

**Comment by nphyatt** [comment]
The error appears to be from this line: https://github.com/ionic-team/cordova-plugin-ionic/blob/master/www/common.ts#L199 which is converting the response from the server to json I checked the response from the api using the details from your issue (your appId, Channel, version number, etc.) and it is indeed valid json that it returns. My only guess would be that perhaps you didn't whitelist `api.ionicjs.com` in you configuration or something and request to our server are being blocked for some reason in production and whatever is blocking them is returning invalid json.

**Comment by iliraga** [comment]
Hi Nick

Thanks a lot for your answer. This is something I already checked shortly - because the issue happens on all global testing users (independent with what Carrier they are connected) this seems to be OS-Related. On iOS we didn't do anything fancy, there are no interceptors, no URL Blacklists etc. And it only happens on iOS, Android (which uses 1:1 the same App Code) is not related by this.

Strangely it's not happening only on iOS 13, also on Devices with Version 12. Any further Ideas? Is there any whitelisting which has to be done on iOS explicitly?

**Comment by iliraga** [comment]
As an `FYI`, it seems it is also related to a strange issue based on the `cordova-common` - https://github.com/apache/cordova-common/pull/89

Where various plugin configurations are not applied properly. Maybe this is also worth to look into.

**Comment by cagintopkaya** [comment]
Hi,

Same situation here. It's started to happen recently. First thought it was related to iOS 13 but tested with devices which had 12. I see the response object coming from the server while debugging with Safari but couldn't figure out how it fails converting it to JSON.

**Comment by kolbis** [comment]
Any update? Should we expect a fix coming out?

**Comment by deliverymanager** [comment]
+1

**Comment by IbanGF** [comment]
+1

**Comment by IbanGF** [comment]
it works for me now, I added manually to the config.xml in the ios section:
`
        <feature name = "IonicCordovaCommon">
            <param name = "ios-package" onload = "true" value = "IonicCordovaCommon" />
        </ Feature>
        <config-file parent = "IonAppId" target = "* - Info.plist">
            <String> 12345678 </ string>
        </ Config-file>
        <config-file parent = "IonChannelName" target = "* - Info.plist">
            <String> Master </ string>
        </ Config-file>
        <config-file parent = "IonApi" target = "* - Info.plist">
            <String> https://api.ionicjs.com </ string>
        </ Config-file>
        <config-file parent = "IonUpdateMethod" target = "* - Info.plist">
            <String> auto </ string>
        </ Config-file>
        <config-file parent = "IonMaxVersions" target = "* - Info.plist">
            <String> 2 </ string>
        </ Config-file>
        <config-file parent = "IonMinBackgroundDuration" target = "* - Info.plist">
            <String> 30 </ string>
        </ Config-file>
`

Using background update method causes the ios app to hang on splashscreen.

**Comment by bryplano** [comment]
Hey folks,

I just finished working with someone who had this issue, and it does appear to be linked to cordova-common being outdated in some projects.

Here is what I'd recommend, in your local project:

- Delete `package-lock.json`
- Make sure you have explicitly set your `cordova-ios` version to 5.1.1 in `package.json`
- Delete the `node_modules`, `www`, `platforms` and `plugins` directories
- Run `npm install`
- Run `ionic cordova platform add ios`
- Run `npm ls cordova-common` (ensure it lists `cordova-common 3.2.1` with this command)

Then commit to Appflow and run a Package build or build your iOS app locally. This new build should properly be able to download a new live update, so once that is done, commit a live update and see if it works properly.

**Comment by DuaneQ** [comment]
@bryplano I've been having this issue with Android not ios.

`Failed to load resource: the server responded with a status of 404 ()
polyfills.js:3040 Unhandled Promise rejection: Error Status 404: App not found ; Zone: <root> ; Task: Promise.then ; Value: Error: Error Status 404: App not found
    at IonicDeployImpl.<anonymous> (/plugins/cordova-plugin-ionic/dist/common.js:291)
    at step (/plugins/cordova-plugin-ionic/dist/common.js:37)
    at Object.next (/plugins/cordova-plugin-ionic/dist/common.js:18)
    at fulfilled (/plugins/cordova-plugin-ionic/dist/common.js:9)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (polyfills.js:2749)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (polyfills.js:2508)
    at polyfills.js:3247
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.js:2781)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (polyfills.js:2553)
    at drainMicroTaskQueue (polyfills.js:2959) Error: Error Status 404: App not found
    at IonicDeployImpl.<anonymous> (http://localhost/plugins/cordova-plugin-ionic/dist/common.js:291:35)
    at step (http://localhost/plugins/cordova-plugin-ionic/dist/common.js:37:23)
    at Object.next (http://localhost/plugins/cordova-plugin-ionic/dist/common.js:18:53)
    at fulfilled (http://localhost/plugins/cordova-plugin-ionic/dist/common.js:9:58)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost/polyfills.js:2749:26)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost/polyfills.js:2508:43)
    at http://localhost/polyfills.js:3247:34
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost/polyfills.js:2781:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost/polyfills.js:2553:47)
    at drainMicroTaskQueue (http://localhost/polyfills.js:2959:35)
api.onUnhandledError @ polyfills.js:3040`

I followed your steps and I get this

`├─┬ cordova-android@5.2.2
│ └── cordova-common@1.4.1 
└─┬ cordova-ios@5.1.1
  └── cordova-common@3.2.1 `

should cordova-common for android be the same as iOS version?

**Comment by bryplano** [comment]
@DuaneQ is your version of `cordova-android` **actually** 5.2.2? If so, that is absolutely ancient...

8.1.0 should be the latest (as of this posting: https://cordova.apache.org/announcements/2019/09/17/cordova-android-release-8.1.0.html) and is what should be used - but if you've been running `cordova-android` 5.X, you're going to have other problems updating your project, not just related to this plugin.

**Comment by DuaneQ** [comment]
Thanks @bryplano .  I was stuck with Android and couldn't even build the project anymore.
`
├─┬ cordova-android@8.1.0
│ └── cordova-common@3.2.1 
└─┬ cordova-ios@5.1.1
  └── cordova-common@3.2.1  deduped`
  I upgraded to Cordova 8.1 and I'm back to being able to build but I'm still facing this issue whenever I launch the project.

But I'm still getting this error when ever I launch the app on an android device 

`Failed to load resource: the server responded with a status of 404 ()
polyfills.js:3044 Unhandled Promise rejection: Error Status 404: App not found ; Zone: <root> ; Task: Promise.then ; Value: Error: Error Status 404: App not found
    at IonicDeployImpl.<anonymous> (plugins/cordova-plugin-ionic/dist/common.js:291)
    at step (plugins/cordova-plugin-ionic/dist/common.js:37)
    at Object.next (plugins/cordova-plugin-ionic/dist/common.js:18)
    at fulfilled (plugins/cordova-plugin-ionic/dist/common.js:9)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (polyfills.js:2753)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (polyfills.js:2512)
    at polyfills.js:3251
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.js:2785)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (polyfills.js:2557)
    at drainMicroTaskQueue (polyfills.js:2963) Error: Error Status 404: App not found
    at IonicDeployImpl.<anonymous> (http://localhost/plugins/cordova-plugin-ionic/dist/common.js:291:35)
    at step (http://localhost/plugins/cordova-plugin-ionic/dist/common.js:37:23)
    at Object.next (http://localhost/plugins/cordova-plugin-ionic/dist/common.js:18:53)
    at fulfilled (http://localhost/plugins/cordova-plugin-ionic/dist/common.js:9:58)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost/polyfills.js:2753:26)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost/polyfills.js:2512:43)
    at http://localhost/polyfills.js:3251:34
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost/polyfills.js:2785:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost/polyfills.js:2557:47)
    at drainMicroTaskQueue (http://localhost/polyfills.js:2963:35)`

Any ideas?

**Comment by anjob1** [comment]
@bryplano thanks for the help, although I'm still getting an issue as above even after taking those steps.

I'm using cordova-ios@5.1.1 & cordova-common@3.2.1. I'm using cordova@9.0.0

Building this locally through Xcode 11.2.1

It's worth noting that this is working on Android, but I haven't been able to get it working on iOS for the last 3 months or so.

I used to build the app via Ionic Pro in the cloud, but needed to add push notifications. The only way around this was to build it locally, but now it seems Ionic Deploy won't work when I take this route.

I have whitelisted https://api.ionicjs.com in my config file as well. 

Any insight into this at all would be much appreciated.

What I've found is that after cordova-common@3.2.1 none of the preferences get written to the correct plist file in the app on iOS as briefly touched on by @IbanGF above. This means you need to add the preferences manually. Even after doing this, and seeing the correct values appear in the console, I get this

`2020-03-16 21:51:27.069146+1100 The Clean 5[1964:911741] calling _sync
2020-03-16 21:51:27.069300+1100 The Clean 5[1964:911741] WARN: {"line":3520,"column":45,"sourceURL":"ionic://localhost/polyfills.js"}
2020-03-16 21:51:27.069448+1100 The Clean 5[1964:911741] WARN: Sync failed. Defaulting to last available version.
2020-03-16 21:51:27.069482+1100 The Clean 5[1964:911741] calling _reload
2020-03-16 21:51:27.069509+1100 The Clean 5[1964:911741] done _reloading
2020-03-16 21:51:27.069538+1100 The Clean 5[1964:911741] Ionic Native: deviceready event fired after 780 ms`
