### ISSUE TITLE
Deploy crashes with Angular 9 / Ivy

### ISSUE THREAD

**Issue by cyrilletuzi** [ionic-team/cordova-plugin-ionic#235]
**Describe the bug**
Using `Deploy` in Angular 9 / Ivy crashes the whole app: it builds but does not launch at all, with a vague `Zone` error.

**To Reproduce**
1. `ionic start`, Angular, no Capacitor
2. Update to Angular 9: `ng update @angular/core @angular/cli`
3. Add Cordova: `ionic cordova prepare ios`
4. Running the app is OK at this step
5. Add Deploy: `ionic deploy add --update-method=none --app-id="YOUR_APP_ID" --channel-name="YOUR_CHANNEL_NAME"`
6. Add `Deploy` from `cordova-plugin-ionic/dist/ngx` in `AppModule` `providers` and/or inject `Deploy` in `AppComponent`
7. Now the app is blocked on splash screen

**Additional context**
- Done the example with Cordova because `ionic deploy add` was failing on a blank project with Capacitor, but I have the same issue with Capacitor in a real world project
- Works if disabling Angular Ivy (`"enableIvy": false` in `angularCompilerOptions` of `tsconfig.json`)

**Comment by dotNetkow** [comment]
Thanks for the issue! If you haven't already, I would send a note over to support@ionic.io - they can investigate.

**Comment by tlancina** [comment]
Thanks for the issue! Should be fixed in 5.4.7, if it's still throwing up errors please let us know.

**Comment by cyrilletuzi** [comment]
I confirm the issue is fixed, thanks a lot for the quick fix!
