### ISSUE TITLE
Plugin documentation incorrect / missing / confusing

### ISSUE THREAD

**Issue by DavidTalamona** [ionic-team/cordova-plugin-ionic#26]
I tried to find some documentation on the live deployment process of Ionic pro and found the following, each one with its own issues / confusion:

1. http://ionicframework.com/docs/pro/deploy/plugin-api.html
- According to this doc `IonicCordova.deploy.download` responds with `true` or `false` but when looking into the code only `true` is possible. Even if there would be a `false` returned it would not make sense to proceed with extraction in this case. An error should be displayed then.
- According to this doc `IonicCordova.deploy.extract` responds with `true` or `false` but when looking into the code only `done` is possible. **The suggested code example would never extract the update!!!** Proceeding with a `false` value would not make sense in this case neither.

2. https://github.com/ionic-team/cordova-plugin-ionic
Return or responding (in case of callbacks) values / types are not defined. What happens when e.g. `IonicCordova.deploy.download(success, failure)` is called. I'm missing some real documentation about methods, callbacks, types, ...

3. https://ionicframework.com/docs/native/pro/
Same issue as with point 2. This is not really a doc that tells me how to use this plugin (wrapper in this case). The definition of `deploy` is almost funny - no hints, no links, nothing.
Besides the native wrapper of Ionic (should be the preferred way of interacting with this plugin, in my opinion) is not mentioned anywhere in the above docs.

4. http://ionicframework.com/docs/pro/monitoring/
There is some confusion with the "pro client" which is also called "pro". It took me some time to understand the difference and in addition https://www.npmjs.com/package/@ionic/pro tells me nothing about the class and available methods / properties **and the linked github project (https://github.com/ionic-team/ionic-pro-agent) does not even exist!!**

**Comment by timbru31** [comment]
@mlynch - maybe you can create a dedicated GitHub project for documentation issues as there is currently no good way to transparently report errors in your various docs.

**Comment by ncapito** [comment]
@DavidTalamona  thanks for filing this we had the same issue.  The documentation for pro is almost comical.  They show an example of comparing a boolean (that the documentations ays will be returned) to a string.  e.g. ` if (res === 'true') {` which would never eval to true, but the good news is it returns `res=done`  instead.

**Comment by mlynch** [comment]
HI all, thanks for the feedback. We're working on unifying the plugin with the pro client, so you won't interface with this plugin directly. That also means we're working on improving the docs around that SDK. We know things are a bit all over the place right now and it's a priority to clean them up.

Stay tuned.

**Comment by matthewkremer** [comment]
Hey @DavidTalamona @timbru31 @ncapito, I've been working on integrating Deploy with our Pro Client for the past week :) I don't have the documentation completed yet, but would love to share with you guys and get your feedback! Shoot me an email matt[at]ionic.io and I'll get you hooked up.

**Comment by Fuiste** [comment]
With the launch of the new docs and updates to the plugin API, this should be addressed now.

Sorry for the confusion, check out the new docs here -> https://ionicframework.com/docs/pro/deploy
