### ISSUE TITLE
GIT interaction & documentation of IONIC pro

### ISSUE THREAD

**Issue by DavidTalamona** [ionic-team/cordova-plugin-ionic#28]
Not sure if this issue is at the correct position here but I did not find a way of giving feedback to the IONIC pro dashboard / documentation.

First issue is I'm not able of deleting branches on the `ionic` remote. I played around with it and now I have some branches that I don't need anymore. I want to get rid of them but the IONIC git server responds with `remote: Error: only pushes are allowed. remote: error: hook declined to update refs/heads/ionic-prod failed to push some refs to 'git@git.ionicjs.com:XXX/YYY.git'`.

Second is a feedback to the documentation of this whole "pro" way of submitting apps to IONIC.
It would have been nice if I have had some info about the second remote that is added to my GIT repo. I'm sure most people don't know about this feature of GIT and would be scared or confused at first.
A small explanation about the capabilities of GIT handling two or more remotes would have been nice.
Also, the hint that branches must be created locally, not pushed to remote "origin" but only to "ionic".
I'm not a newbie with GIT but neither a crack. Think I roughly represent the great mass of users and such advice would have been helpful to me.

**Comment by janpio** [comment]
> Not sure if this issue is at the correct position here

No.

**Comment by DavidTalamona** [comment]
@janpio Thank you for this very constructive answer ;o)
That's what I was assuming myself but if not here then were? I did not find any isuue tracker for the ionic PRO backend nor the documentation.

**Comment by janpio** [comment]
You mentioned that you are not sure, I told you the reality so you can be sure - I thought that was very constructive.

I also don't have a better answer. You could post this in the "Ionic Pro" category at https://forum.ionicframework.com/, but the Ionic (Pro) team is not active there. The support system has a "Report services bug or issue" entry: http://ionicframework.com/support#support This might be your best bet.
