### ISSUE TITLE
Does this work with angular 1?

### ISSUE THREAD

**Issue by kr4ng** [ionic-team/cordova-plugin-ionic#30]
I have an ionic1 app that I am trying to migrate from legacy to ionic pro. Would like to use ionic pro deploy but am having trouble getting this package working with angular/ionic 1

**Comment by janpio** [comment]
If you have problems getting it to work, please post in the "Ionic Pro" category at https://forum.ionicframework.com and include information what you are doing and what is happening (and your `ionic info` output).

**Comment by Fuiste** [comment]
This plugin should work just fine in Ionic 1, as the cordova js API will exist on `window` no matter which framework the app is build with.
