### ISSUE TITLE
Unable to run Live Deploy when using manual update method

### ISSUE THREAD

**Issue by nikhilmathew** [ionic-team/cordova-plugin-ionic#34]
i added cordova plugin deploy with update method none 
and then added the manual update code in the app.component.ts file of the ionic project
when i compile the code to ios is throws an exception, details below

2017-11-29 09:45:09.394339+0530 Sports Unity[2501:832055] [User Defaults] Attempt to set a non-property-list object <null> as an NSUserDefaults/CFPreferences value for key channel
2017-11-29 09:45:09.395096+0530 Sports Unity[2501:832055] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object null for key channel'
*** First throw call stack:
(0x1b813b3d 0x1aa9b067 0x1b813a85 0x1b8447e7 0x1b7a6843 0x1b844ad3 0x1b844c47 0x1b7c5cfb 0x1b844ad3 0x1b844c47 0x1b844c6d 0x1b7c81df 0x1b7c7b21 0x1b7c80a1 0x1b84a2f7 0x1b84db3b 0x1c08406b 0x13e7c9 0x23b891 0x163f69 0x163dbb 0x1656a3 0x23cefd63 0x23c9814b 0x23c99b67 0x23c99aaf 0x23c99a25 0x23b2a07b 0x23c7cb41 0x23afd52d 0x23aff521 0x1f67cc5b 0x1f67ce0f 0x1b7cffdd 0x1b7cfb05 0x1b7cdf51 0x1b7211af 0x1b720fd1 0x1cecbb41 0x20aa9a53 0xe2b43 0x1af0e4eb)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by nikhilmathew** [comment]
this error occured with 2.0.3 version of cordova-plugin-ionic

**Comment by iliraga** [comment]
Have you been able to solve this? I don't know why the guys from driftyco don't answer.

**Comment by Fuiste** [comment]
I can't reproduce this issue on plugin version 4.0.0 using multiple devices.

We recently rewrote all of our docs as well, and launched a client to help with manual plugin use, which may help here -> https://ionicframework.com/docs/pro/deploy
