### ISSUE TITLE
Very large .ipa after adding the plugin (Steps to reproduce ...)

### ISSUE THREAD

**Issue by deliverymanager** [ionic-team/cordova-plugin-ionic#37]
My .ipa was 5.4MB and after adding the plugin it became 63.1MB

This is reproducible.
Is this normal? This is a huge issue!

**cordova plugins**
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-camera 4.0.1 "Camera"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-ionic 2.0.4 "IonicCordova"
cordova-plugin-proguard 1.0.0 "Cordova plugin ProGuard"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"

**ionic info**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : ios 4.5.4
    Ionic Framework   : ionic1 1.3.3

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.4
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/adomvris/Library/Android/sdk/

Misc:

    backend : pro

**Comment by deliverymanager** [comment]
**Steps to reproduce**

```
ionic start testProject blank --type ionic1
Ionic cordova platform add iOS
Ionic Cordova build iOS —release
```

in Xcode if we export the app it is just **3.6MB**

Then I add the cordova-plugin-ionic
`ionic cordova plugin add cordova-plugin-ionic --variable APP_ID='-' --variable UPDATE_METHOD='none' --variable CHANNEL_NAME='-'`

When I added it gave me the following feedback:
```
Update IOS build setting SWIFT_OBJC_BRIDGING_HEADER to: "$(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h" for build configuration Debug
Update IOS build setting SWIFT_OBJC_BRIDGING_HEADER to: "$(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h" for build configuration Release
Update IOS build setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to: YES for build configuration Debug
Update SWIFT version to 3.0 Debug
Update IOS build setting SWIFT_OPTIMIZATION_LEVEL to: -Onone for build configuration Debug
Update IOS build setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to: YES for build configuration Release
Update SWIFT version to 3.0 Release
```
Then after exporting the ipa from xcode it is **61.3MB**


I hope there is a way to solve this, as it is very very huge issue.

**Comment by deliverymanager** [comment]
From what I understand the cordova-plugin-ionic is using a cocoapod that has swift code.
This means that the swift libraries need to be embedded in the app bundle.
This is probably why the plugin is making the bundle 20 times larger.
This is so so bad...

I hope there is a way for this to change otherwise this is totally a deal breaker.

**Comment by deliverymanager** [comment]
@mlynch

**Comment by deliverymanager** [comment]
The only part of the code using swift code is getAppInfo feature of the plugin. 
This is a new feature that there wasn't in the legacy deploy plugin, so could this be a mistake that this was written in swift? @mlynch

**Comment by deliverymanager** [comment]
OK. So what I ended up doing was forking the github project.
https://github.com/deliverymanager/cordova-plugin-ionic.git

I removed the swift code and the dependency for the cordova-plugin-add-swift-support
I replaced the swift code with C.
The only data the getAppInfo returns in my case is "platform, bundleVersion, bundleName"
It does not return platformVersion.

**Comment by mlynch** [comment]
Thanks for the debugging info here, that seems like too large of an increase to just be swift, I wonder if that swift compat plugin is doing something else...

**Comment by deliverymanager** [comment]
From what i saw it just adds some flags to plist file of ios, in order to embed the swift libraries.
Otherwise the cocoa pods does not do this by default.
I needed to remove the swift code (IonicCordova.getAppInfo) from the plugin and its dependency to the cordova-plugin-add-swift-support.
You may check out my forked repo to see the C code that replaces the Swift code.
I have tested my repo a lot and it works without any issue so far in both Android and iOS.

**Comment by timbru31** [comment]
We have an increase of >30MB, too with the new Ionic plugin. Is there any solution for this problem or at least the known reason for this issue?

**Comment by mlynch** [comment]
Thanks for the info, we're going to remove the Swift code and reduce the size of this library.

Until Apple ships the stdlib we're best served keeping this one Obj-c

**Comment by mlynch** [comment]
@deliverymanager I'm seeing a number of other changes in your project. Are those things we should pull in as well? I'm curious, for example, what the impact is of the changes made to `plugin.xml`

**Comment by deliverymanager** [comment]
The changes were made because there is another bug in the plugin.
It didnot remove the downloaded snapshots correctly.
This is also resolved in the repo.

The changes to the plugin.xml were made because I replaced the swift code files with the new code in order to keep the same functionality of the plugin.

**Comment by mlynch** [comment]
Removed Swift so sizes should be smaller. Also fixed a few build errors
