### ISSUE TITLE
Compatibility with cordova-plugin-splashscreen v5+

### ISSUE THREAD

**Issue by timbru31** [ionic-team/cordova-plugin-ionic#40]
Currently my installation is throwing a warning:
```
Failed to install 'cordova-plugin-ionic': CordovaError: Version of installed plugin: "cordova-plugin-splashscreen@5.0.1" does not satisfy dependency plugin requirement "cordova-plugin-splashscreen@^4.0.0". Try --force to use installed plugin as dependency.
```

Looking at the changelog v5 of the cordova-plugin-splashscreen, it does only remove deprecated platforms which should not work with Ionic anyways. (see https://github.com/apache/cordova-plugin-splashscreen/blob/master/RELEASENOTES.md). Can you possibly bump the dependency to `^5.0.0` in your `plugin.xml` to silence this warning?

If you agree to this change, I'm happy to make a PR.

**Comment by Fuiste** [comment]
I'm fine with this change, if you put up a PR it will go out in the next version of the plugin.

👍
