### ISSUE TITLE
"background" mode not working?

### ISSUE THREAD

**Issue by mgrbose** [ionic-team/cordova-plugin-ionic#45]
Hello, I am using "background" mode. And it seems that this will show the SplashScreen till the download is complete and unzipped. Actual update to the new version will show in the next app load. But the download should be happening in the background and SplashScreen should not be impacted because of the download delays. Am I missing anything ? 

I can confirm that right after "IONIC.DEPLOY.REMOVE: Removed www.zip" log, the SplashScreen will be hidden. 

I am using Android Device. 

My config.xml:

```
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="AndroidLaunchMode" value="singleTask" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="loadUrlTimeoutValue" value="700000" />
```

ionic info
cli packages: (/usr/local/lib/node_modules)
ionic/cli-utils : 1.19.1
ionic (Ionic CLI) : 3.19.1

global packages:
cordova (Cordova CLI) : 7.0.1

local packages:
ionic/app-scripts : 3.1.2
Cordova Platforms : android 6.3.0
Ionic Framework : ionic-angular 3.9.2

System:
Android SDK Tools : 26.1.1
ios-deploy : 1.9.0
Node : v8.3.0
npm : 5.3.0
OS : macOS Sierra
Xcode : Xcode 9.2 Build version 9C40b

Environment Variables:
ANDROID_HOME : /Users/***/Library/Android/sdk

Misc:
backend : pro

**Comment by Fuiste** [comment]
I've just released version 3.1.2 of the plugin, which should solve this issue.
