### ISSUE TITLE
Make debug mode configurable

### ISSUE THREAD

**Issue by timbru31** [ionic-team/cordova-plugin-ionic#46]
It would be a good enhancement if the user could make the debug screen configurable - we'd like to keep the ability to debug the native packages (.ipa, .apk), but always apply the latest deployment without the debug alert.
Can you add a configuration flag to suppress the debug screen?

**Comment by ztecharoberts** [comment]
Created a pull req for this. https://github.com/ionic-team/cordova-plugin-ionic/pull/49

**Comment by Fuiste** [comment]
This was released in plugin 3.1.0, thanks for the PR!

One side note, I renamed the variable to `WARN_DEBUG` and added a default value.
