### ISSUE TITLE
README says the max store property is MAX_VERSIONS, but code says it's MAX_STORE

### ISSUE THREAD

**Issue by timbru31** [ionic-team/cordova-plugin-ionic#47]
The README.md is incorrect regarding the MAX_VERSIONS/MAX_STORE config.
It should be MAX_STORE, since this is the value defined in the `plugin.xml` (https://github.com/ionic-team/cordova-plugin-ionic/blob/master/plugin.xml#L22)

**Comment by Fuiste** [comment]
Good catch, this is fixed in 3.1.0
