### ISSUE TITLE
Debug mode for Android

### ISSUE THREAD

**Issue by tlancina** [ionic-team/cordova-plugin-ionic#5]
https://stackoverflow.com/questions/23844667/detect-if-i-am-in-release-or-debug-mode-in-android

**Comment by Fuiste** [comment]
https://github.com/ionic-team/cordova-plugin-ionic/blob/master/src/android/IonicDeploy.java#L120

🤔

In all seriousness, is this not working on your test phones?  I only tested on a Nexus 6P.

**Comment by tlancina** [comment]
Forgot I was on the no-zip branch because of the native dependency clash, I'll update it thanks!
