### ISSUE TITLE
Regex for cordova.js will remove other scripts

### ISSUE THREAD

**Issue by timbru31** [ionic-team/cordova-plugin-ionic#52]
The regex to find the cordova.js will remove other script tags, if they are on the same line. This is a very serious issue, since a live deploy can remove script tags and render the app non functional.

Try it yourself, this is the regex for the cordova.js on e.g. https://www.debuggex.com/
`<script src=(\"|')(.*\\/|)cordova\.js.*(\"|')>.*<\/script>` (see https://github.com/ionic-team/ionic-plugin-deploy/blob/master/src/ios/IonicDeploy.m#L440)

And now the two sets of test data:
This one with line breaks in between, only `cordova.js` is replaced (i.e. works as intended)
```html
<script src="cordova.js"></script>
<script type="text/javascript" src="scripts.669faa1506ded556b686.bundle.js"></script>
<script type="text/javascript" src="main.fa42917090b67bcd270d.bundle.js"></script>
```

This one is a minified (i.e. production version) that does not work, since the regex matches all scripts:
```html
<script src="cordova.js"></script><script type="text/javascript" src="scripts.669faa1506ded556b686.bundle.js"></script><script type="text/javascript" src="main.fa42917090b67bcd270d.bundle.js"></script>
```

/cc @mlynch

**Comment by timbru31** [comment]
Broken on Android, too: https://github.com/ionic-team/cordova-plugin-ionic/blob/master/src/android/IonicDeploy.java#L956

**Comment by timbru31** [comment]
Something like https://www.debuggex.com/r/R8FHUyr_ioo-Tn6t might work better

**Comment by Fuiste** [comment]
Good catch.  Sorry for the delay here, but I'm finishing up a release of the plugin which should address these issues today.  Look out for v3.1.0

**Comment by Fuiste** [comment]
Just published the new plugin!

**Comment by timbru31** [comment]
Thanks for the update @Fuiste, however I believe the new regex is still broken: https://www.debuggex.com/r/T-qAq5KwJCzP_1en

**Comment by Fuiste** [comment]
Oh, looks like it is.  Silly copy on my part, sorry there!  I'll push a new version within the hour

**Comment by timbru31** [comment]
Now it looks good - thanks for the quick fix! 🎉
