### ISSUE TITLE
plugin add error

### ISSUE THREAD

**Issue by jQrgen** [ionic-team/cordova-plugin-ionic#54]
The dependency is forfilled? Should work?

```
lolmac:flare-ionic2 jqrgen$ cordova plugin add cordova-plugin-ionic --save --variable APP_ID="<>" --variable CHANNEL_NAME="Master" --variable UPDATE_METHOD="none"
Installing "cordova-plugin-ionic" for ios
Installing "cordova-plugin-add-swift-support" for ios
Failed to install 'cordova-plugin-ionic': CordovaError: Version of installed plugin: "cordova-plugin-splashscreen@5.0.1" does not satisfy dependency plugin requirement "cordova-plugin-splashscreen@^4.0.0". Try --force to use installed plugin as dependency.

```

**Comment by Fuiste** [comment]
Version 3.x.x of the plugin requires cordova splashscreen 5.0.1 or higher, whereas previous versions required splashscreen 4.x.x. 

I can't replicate this specific error when I have the deps installed, so my guess is either you have a differennt version of splashscreen than the one it's expecting, or Cordova is being difficult.  You could try the `--force` flag here, as the major version bump in the splash plugin shouldn't have a breaking effect on the Ionic plugin.
