### ISSUE TITLE
Browser error

### ISSUE THREAD

**Issue by jQrgen** [ionic-team/cordova-plugin-ionic#55]
I get the following errors in browser:

![screen shot 2018-01-31 at 14 21 59](https://user-images.githubusercontent.com/3964957/35625310-88e37f16-069a-11e8-940b-347657119cd6.png)

the cordova-plugin-ionic plugin is currently installed.

**Comment by jQrgen** [comment]
The 2. error over was fixed by: npm install --save @ionic/pro.

1. error still unresolved

**Comment by Fuiste** [comment]
This plugin does not support the browser, as it leverages native functionality.

**Comment by jQrgen** [comment]
What about disabling the errors when a project containing the error uses ionic serve?

for example this pseudokode:

```js
if(ionicPlatform.is('cordova'))
  throw err
```
