### ISSUE TITLE
branch no-zip update

### ISSUE THREAD

**Issue by eherve** [ionic-team/cordova-plugin-ionic#56]
Hi,

Thanks for your work.

Quick question, does the no-zip branch is still maintained and will it be updated along the master ?
I'm using the no-zip to avoid conflict with the zip plugin.

Regards,

**Comment by Fuiste** [comment]
Unfortunately, the no-zip is no longer maintained, but a solution to the zip conflict is definitely something we'd like to tackle.

**Comment by eherve** [comment]
Thank you for your reply, we really need to use the cordova zip plugin.
