### ISSUE TITLE
Error duplicate symbols for zip file in ios

### ISSUE THREAD

**Issue by eherve** [ionic-team/cordova-plugin-ionic#58]
Impossible to build ios if cordova-plugin-zip is installed.
There is a symbol conflict (duplicate) between zip files from this plugin and zip files from cordova-plugin-zip.

Is it possible to remove the zip files from this plugin and make a dependance to cordova-plugin-zip ?
Or any other solution ?

We are using the no-zip branche for now but the branche is not maintained.

Thanks

**Comment by Fuiste** [comment]
Sorry for the inconvenience there.  I'm going to be keeping `no-zip` up to date going forward, at least until there's a more elegant solution in place.  It should currently match plugin version 3.1.3

**Comment by adrian999999** [comment]
@Fuiste How do I install the no-zip branch?
