### ISSUE TITLE
Zip extract callback method returns different values for Android vs iOS

### ISSUE THREAD

**Issue by andreassolemkjaer** [ionic-team/cordova-plugin-ionic#59]
When handling the update method manually using the "none" update method, the return value from `IonicCordova.deploy.extract` differs between Android and iOS.

Android IonicDeploy.java:
```
private void unzip(String zip, String location, CallbackContext callbackContext) {
...
  callbackContext.success("true");
```

iOS IonicDeploy.m:

```
- (void)zipArchiveProgressEvent:(NSInteger)loaded total:(NSInteger)total {
...
  pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"done"];
```

**Comment by Fuiste** [comment]
Looks like this was a bug introduced in 3.1.1.  I've just released 3.1.2, which should fix the issue.
