### ISSUE TITLE
Latest deploy is reverted to installed build

### ISSUE THREAD

**Issue by demency** [ionic-team/cordova-plugin-ionic#61]
**Hi ionic developers and users**, today i'll to show you one issue what i'm facing now. 

I'm trying to use the Live Deploy service, but it apparently doesn't works...

## Description

After the installation and configuration of the plugin i deploy my app successfully via XCode to my device (iPad). So after that... i change and upload my code to test the service in auto mode. So, i open the app and it show me the debug message of "Debug... update or keep the version". If you accept the deploy, the new version is deployed with my changes.

All is done for now! but... if i close and open the application. The change is reverted and i've got the old version.  

## Ionic info

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 2.0.0

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.4
    npm        : 5.6.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by Fuiste** [comment]
Can you confirm whether this issue persists in version 4.0.0 of the plugin?

Also, does it still happen if you install the plugin with the `WARN_DEBUG` install flag set to `false`?  This will disable the warning popup and would help me zero in on the issue.

**Comment by timbru31** [comment]
This sounds like #23 - and yes still the case with 4.1.3

**Comment by PauCodina** [comment]
It's true, version v4.0.1 works well for me.
Thanks @timbru31

**Comment by timbru31** [comment]
You’re welcome, glad I could help!
Now it’s just a matter of weeks until an Ionic dev replies :)
