### ISSUE TITLE
Upgraded app from deprecated plugin not get the new app_id

### ISSUE THREAD

**Issue by lempere** [ionic-team/cordova-plugin-ionic#62]
I try to upgrade the deprecated plugin *ionic-plugin-deploy* to *cordova-plugin-ionic* but the ionicpro app created a new app_id. With  the new app_id I can't process the update in devices previously installed with the deprecated plugin.

If the app have already installed the app_id is set in the SharedPreferences, when I install and deploy the new app with the new plugin the plugin will read the SharedPreferences already set and not the new app_id from configuration.

https://github.com/ionic-team/ionic-plugin-deploy/blob/master/src/android/IonicDeploy.java#L336
https://github.com/ionic-team/cordova-plugin-ionic/blob/master/src/android/IonicDeploy.java#L398 

Some solution is clear the app chache. Then the plugin will read the configuration and not the SharedPreferences

How this could be solve? Without deleting the cache

**Comment by Fuiste** [comment]
You can use the `init` function on the plugin to set a new app ID, which will be persisted to the shared preferences.

**Comment by lempere** [comment]
This didn't work. The init function in the IonicDeploy.init or the Pro.init get the appID from the SharedPreferences. 
I can't change the appID in runtime after is set in the SharedPreferences.
I saw that the monitoring url have the appID changes but when I try to do a version check the plugin download from the older appID.

I thing the plugin need to check if the appID is the same from the SharedPreferences and update it accordingly.
