### ISSUE TITLE
Error: cordova already defined

### ISSUE THREAD

**Issue by deliverymanager** [ionic-team/cordova-plugin-ionic#64]
After updating to the new version 3.1.2 from 2.0.4 I get an 
Error: cordova already defined
exactly after downloading a new deploy snapshot.
I have actually checked the index.html and I can see 2 cordova declarations to the downloaded version.

Has something changed to the plugin and now we should remove the cordova.js from the index.html before uploading a deploy snapshot to Ionic pro?

**Comment by deliverymanager** [comment]
In iOS ionicDeploy.m I saw that there is a change to the regex that finds cordova.js
I think there is an error there, as the problem that I am facing is that it does not find the cordova.js in the html and re-injects it cause the error.

+    String cordovaRegexString = "<script src=(?:\"|')(?:[\\w\\-\\:/\\.]*)?cordova\\.js(?:[\\.\\w]*)?(?:\"|')>(.|[\\r\\n])*?</script>";  // Find cordova.js

@Fuiste Did you actually test it on iOS by downloading a snapshot from ionic deploy?

Thank you!

**Comment by deliverymanager** [comment]
I think I found the problem in my case.
The new regex catches also the 
 <script src="lib/ngCordova/dist/ng-cordova.js"></script>
that I have in my index.html
That is why is replaces the ng-cordova.js too

**Comment by deliverymanager** [comment]
From what I understand the previous regex
<script src=(\"|')(.*\\/|)cordova\\.js.*(\"|')>(.|[\r\n])*<\\/script>
did not actually match the 
"<script src="cordova.js"></script>"
The new regex 
<script src=(?:"|')(?:[\w\-\:/\.])?cordova\.js(?:[\.\w])?(?:"|')>(.|[\r\n])*?</script>
finds it.

But the issue might be that it does not replace this but it adds one more time the cordova.js like it did before?

**Comment by deliverymanager** [comment]
The regex should be:
<script src=(?:\"|')(?:[\\w\\-\\:/\\.]*\/)?cordova\\.js(?:[\\.\\w]*)?(?:\"|')>(.|[\\r\\n])*?</script>

**Comment by Fuiste** [comment]
This should be solved in plugin 3.1.3
