### ISSUE TITLE
Splashscreen hangs / Cordova not loaded on iOS

### ISSUE THREAD

**Issue by blumk** [ionic-team/cordova-plugin-ionic#65]
After upgrading the plugin from 2.0.4 to 3.1.2 I've noticed two issues:
- App hangs on Splashscreen. Manually closing the app and re-opening solves the issue.
- Sometimes cordova is not loaded (e.g. accessing plugins throws an exception). This happens after manually closing the app (see above)
- App start-up takes about 2-3 seconds longer (compared to v2.0.4)

@Fuiste it looks like you've fixed the issue on Android a couple days ago. Have you thoroughly tested the plugin on iOS?

**Comment by blumk** [comment]
@Fuiste v4.0.0 fixed the cordova issue. The splashscreen issue exists:
- App hangs initially on Splashscreen / white screen appears. Manually closing the app and re-opening solves the issue. Occurs only after installing the app and initially loading the app.

**Comment by Fuiste** [comment]
I've used an iOS device when testing 4.0.0, and didn't see this issue.

Are you seeing an any errors during startup, while the splashscreen is present?

**Comment by blumk** [comment]
Will test it again with the 4.0.0 release.

**Comment by blumk** [comment]
I can no longer reproduce the issue with the 4.0.0, thx for the fix!
