### ISSUE TITLE
How to use new Live deploy Ionic  Pro

### ISSUE THREAD

**Issue by mrezzaaa** [ionic-team/cordova-plugin-ionic#7]
Hi,i'm having problem using this feature.
When i'm deploy new version into git ionic branch , always No update available which means when checking a new version is always returned false . 
case : 
1. App build in android using version 0.0.1 . config from config.xml,already set using UPDATE_METHOD="background" /"auto" / "none" .I had use them all for looking which one will works.
2. Adding some chages to page 
3. changing version on config.xml to version 0.0.2 
4. push to ionic git using `git push ionic master` 
5. changing deploy channel to latest commited 
6. Open app,close (when using update method auto/background)
7. Find another tutorial [here](https://code.tutsplus.com/tutorials/get-started-with-ionic-services-deploy--cms-28827)
nothing update works .
please give me a clear tutorial how to use this from start .
If there need programatically code. Where i put the code , and which example code.
this problem is make me stuck for 2 days .

On the video demo on ionic pro website ,i follow that and nothing happen with old version.

**Comment by Kapsul-Brice** [comment]
Same problem here. Nothing gets updated, emulator + device remains with old app version.
The new version only appears in Ionic View. A complete step by step tutorial for production updates (without app store approval) would be great.

**Comment by JeremyLopez** [comment]
Same here.  Please advise

**Comment by mrezzaaa** [comment]
Hi guys , i'm solving this problem by myself . 
1. try update ionic cli to latest version
2. Delete project/create new on ionic dashboard.
3. And configure live deploy at start new project after run ionic link 
4. Push to ionic git (git push ionic master) 
5. Make some changes on any page html , then push again 
6. make sure pushed commit compiled successfully on ionic dashboard 
7. Live deploy will be run depends on your mode. I choose mode auto 

Hint: i'm using android and showing data meter on status bar , so i know while apps is downloading new updates and noticed data meter download is going high
