### ISSUE TITLE
Shows oldest version while downloading on AUTO

### ISSUE THREAD

**Issue by jurgen-reconcept** [ionic-team/cordova-plugin-ionic#73]
I'm using the AUTO update which works fine, but while it's still downloading or extracting (not sure which phase exactly) it will show me the oldest version of the content (the one that is in the binary). 

I'd prefer to keep using auto updates, but I was hoping maybe the API provides a way to check what is currently happening. Like show the progress of the download that was already started by the auto update, so I can show an indicator instead of the OLD login screen. However, from this documentation I can only tell there are methods to actually perform the whole process.

I could of course implement the whole update process manually, but the docs say that that is not advised. Any help?

**Comment by jurgen-reconcept** [comment]
Any word on this?

**Comment by tmyers97** [comment]
Did you ever figure this out? My auto updates quit working out of no where and I am not sure what to do.

**Comment by Fuiste** [comment]
Can you confirm this issue persists in version 4.1.6 of the plugin?

**Comment by Fuiste** [comment]
Closing per comments in https://github.com/ionic-team/cordova-plugin-ionic/issues/78

4.1.6 should solve this as well, so long as you're running `cordova-plugin-ionic-webview` version 1.1.19 or older.

If this persists, let me know and I can reopen.
