### ISSUE TITLE
Pro.deploy.checkAndApply(true) fails on Android

### ISSUE THREAD

**Issue by mikejpeters** [ionic-team/cordova-plugin-ionic#75]
I'm using cordova-plugin-ionic@4.1.3 on an Android 7.0 device.

Auto updates succeed, but manually calling `Pro.deploy.checkAndApply(true)` fails to redirect.

The ADB logs show that the `UNZIP_DIR` is being set incorrectly to `app_`:

```
IONIC.DEPLOY.UNZIP: xxx-xxx-xx2
IONIC.DEPLOY.HASVER: Checking xxx-xxx-xx2...
IONIC.DEPLOY.HASVER: xxx-xxx-xx1 == xxx-xxx-xx2
IONIC.DEPLOY.HASVER: No
IONIC.DEPLOY.UNZIP_DIR: /data/user/0/com.example.App/app_
```

So when the redirect occurs it fails (presumably because the version was unzipped to `app_` instead of the correct directory):

```
IONIC.DEPLOY.REDIRECT: Pre-redirect cordova injection exception: java.io.FileNotFoundException: /data/user/0/com.example.App/app_xxx-xxx-xx2/index.html (No such file or directory)
```

I think this is happening because the Android implementation for *extract* uses the "uuid" pref as the unzip location but it's not set yet: https://github.com/ionic-team/cordova-plugin-ionic/blob/11dc78dce7436dadc5bfd3ff4d97378bf6f92174/src/android/IonicDeploy.java#L340-L345

Looking at the code, the "uuid" pref is only set during the download step if the version already exists on the device, otherwise it's set after the update.

**Comment by saral2** [comment]
Any update on this ?

**Comment by saral2** [comment]
@mikejpeters  Thanks your fix is working alright.
