### ISSUE TITLE
Splashscreen hangs on iOS

### ISSUE THREAD

**Issue by iliraga** [ionic-team/cordova-plugin-ionic#76]
Hi there

It's absolutaly not reproducable every time but on most deploys the splashscreen on iOS hangs and doesn't disappear. Multiple reloads fix the problem.

Any easy way of resolving that? We have the setting to "auto" (so it loads and applys the deploy immediately on app start).

Plugin verison is `4.1.3`, iOS Version is `4.5.4`

**Comment by iliraga** [comment]
Was able to get a debug log from XCode Organizer:

It seems it downloads the deploy package in the background (`Download Progress` & `Unzipping Progress`) and afterwards are getting this error:

`default	22:41:49.608684 +0200 Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)`

See here full log file
[WORLD_RUN_FREEZINGSPLASHSCREEN_LOG.LOG](https://github.com/ionic-team/cordova-plugin-ionic/files/1908873/WORLD_RUN_FREEZINGSPLASHSCREEN_LOG.LOG)

**Comment by HugoHeneault** [comment]
@iliraga You can send your issue to ionic support with your paid account to get faster support: https://ionic.zendesk.com/hc/en-us/requests/new

But they might simply say that they'll check it with the devs. You can also give the links to the related issues. :)

**Comment by Fuiste** [comment]
We just released version 4.1.6 of the plugin, which I believe should address this issue.  Let me know if this persists and I can reopen.

**Comment by glebmachine** [comment]
I've got it on 4.1.7
