### ISSUE TITLE
IonicDeploy.m line 524 cases error after snapshot is downloaded

### ISSUE THREAD

**Issue by chrisdelambert** [ionic-team/cordova-plugin-ionic#8]
Hi,

When I use ionic pro live deploy using 'none' for update method, the deploy crashes the app after the snapshot has downloaded.

The problem is in IonicDeploy.m line 24.
The error is : *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'

XCode highlights this block of code as the culprit
 NSArray *matches = [commentedRegex
                                    matchesInString:htmlData
                                    options:0
                                    range:NSMakeRange(0, [htmlData length])];

I am using this code:
IonicCordova.deploy.download(
            appId,
            () => {
              console.log('downloading')
              IonicCordova.deploy.extract(
                appId,
                () => {
                  console.log("extracting");
                  IonicCordova.deploy.redirect(
                    appId,
                    () => {
                      console.log("redirecting");
                      callback(null, true);
                    },
                    (e: any) => {
                      this.handleError(e, callback);
                    }
                  );
                },
                (e: any) => {
                  this.handleError(e, callback);
                }
              );
            },
            (e: any) => {
              this.handleError(e, callback);
            }
          );
        
      
      (e: any) => {
        this.handleError(e, callback);
      }

'redirecting' never gets logged - however 'extracting' gets logged over 400 times.

**Comment by media4learning** [comment]
Note: Same build works flawlessly on Android. This problem is on ios only.

**Comment by Fuiste** [comment]
This is a duplicate issue to https://github.com/ionic-team/cordova-plugin-ionic/issues/12, and is something I'm addressing in v2.0.0

Check out the progress here https://github.com/ionic-team/cordova-plugin-ionic/pull/13

**Comment by Fuiste** [comment]
This should be fixed in version 2.0.0, let me know if it comes up again!

**Comment by media4learning** [comment]
Now the plugin doesn't work at all! https://github.com/ionic-team/cordova-plugin-ionic/issues/14
