### ISSUE TITLE
Deploy 4.1.4 broken subsequent deploys on same binary

### ISSUE THREAD

**Issue by media4learning** [ionic-team/cordova-plugin-ionic#81]
Hi again. cordova-plugin-ionic 4.1.4 fixed the issue with the deploy content not extracting / failing. Now however, there is a new issue.

I have version 1.0.8 of my app. I deploy new content. This works great! Then, I deploy some new content (still on binary version 1.0.8). The app picks up that there is new content. I download and extract. The app redirects to the first bundle of deployed content. It should redirect to the second.

If I start at 1.0.8 and do not download the first deploy. Then downloading and deploying the second deploy works as expected.

I am on cordova-plugin-ionic 4.1.4

Ionic info:
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v8.9.1
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/chrisdelambert/Library/Android/sdk

Misc:

    backend : pro

**Comment by Fuiste** [comment]
We just released version 4.1.6 of the plugin, which addresses an issue which existed during extraction when a version was already present.  Let me know if this solves the issue!
