### ISSUE TITLE
Can't find common.js file

### ISSUE THREAD

**Issue by camdav** [ionic-team/cordova-plugin-ionic#87]
Hi, I have a Ionic 1 project and I'm trying to install cordova-plugin-ionic bui I'm getting the error 
ENOENT: no such file or directory, open '/Users/***/my-app/plugins/cordova-plugin-ionic/dist/common.js'

Can you help me to solve this problem?
Thanks
Davide

**Comment by adrm** [comment]
I had to go to plugins/cordova-plugin-ionic and do `npm install` and `npm run build` to generate the `dist` folder containing the required file. This should not behave this way.

**Comment by nphyatt** [comment]
Thanks for the report! @camdav and @adrm  it was a problem with us publishing with an good `.npmignore` file. Fixed and published a new `alpha` tag. Let me know if you encounter more problems and feel free to ping me!
