### ISSUE TITLE
Ionic deploy reloads twice after first app run

### ISSUE THREAD

**Issue by JustasKuizinas** [ionic-team/cordova-plugin-ionic#9]
Steps
1. Install ionic blank template
2. Configure ionic deploy service and link app too ionic pro
3. Install cordova-plugin-ionic
4. Build android
5. Install app on device

First time I open app on mobile device I get this popup
![Alt text](https://monosnap.com/file/FM19U7Yn9Imni19YQyjLVIPtuAx1Os.png)
I press update then screen turns white app reloads and same popup opens.

But when I shut down and open app, above pop up opens only once.

So the problem is that  when you open app for the first time after install, above popup opens twice.

**Comment by jaapjanfrans** [comment]
the popup is triggered when the deviceready event is fired.  After reloading the app that event fires again as your app is basically restarted (except for the native wrapper around your hybrid app, the html/js portion of your app is being reloaded/restarted), which explains the popup being rendered twice.

you'll only see this when running debug builds of your app as the popup is not shown in release versions of an app.

**Comment by JustasKuizinas** [comment]
@jaapjanfrans on production build I don't see a popup but what happens is:

1. First time I open app after like 5-7 seconds it reloads.
2. I close the app, update some code and push everything to ionic pro.
3. Open app second time and after splash screen I see white screen for a few seconds( seems it's updating) then app starts and is updated.

So on android it has some strange bugs.

**Comment by jaapjanfranstfe** [comment]
Hmm not too sure what could be your issue in a production build , sounds like you're using auto or reload as the update method. i use the 'none' option and handle updating from my own js code.

**Comment by JustasKuizinas** [comment]
@jaapjanfranstfe yes I use auto

**Comment by Fuiste** [comment]
Hey all, this seems to have been an issue with the iOS plugin redirecting in `pluginInitialize` as well as `onReset`, and should be fixed in version 2.0.0, which I'm trying to get out this week.

Check out the progress here https://github.com/ionic-team/cordova-plugin-ionic/pull/13

**Comment by Fuiste** [comment]
This should be fixed in version 2.0.0, let me know if it comes up again!
