### ISSUE TITLE
Android build fails: IonicCordovaCommon.java:83: error: strings in switch are not supported in -source 1.6

### ISSUE THREAD

**Issue by mydoal** [ionic-team/cordova-plugin-ionic#95]
After adding the cordova-plugin-ionic, the android build fails:

ionic cordova run android --verbose

BUILD FAILED in 19s
36 actionable tasks: 34 executed, 2 up-to-date
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\dev\workspaces\web\ionic\rezidnet2\platforms\android\src\com\ionicframework\common\IonicCordovaCommon.java:83: error: strings in switch are not supported in -source 1.6
    switch(action) {
          ^
  (use -source 7 or higher to enable strings in switch)

ionic info:
```
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    Node              : v8.10.0
    npm               : 5.6.0
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : C:\dev\lib\Android\sdk

Misc:

    backend : pro
```

plugin:

```   
 "cordova-plugin-ionic": "^5.0.0-alpha.1",
```

**Comment by nphyatt** [comment]
Could you try using `cordova-plugin-ionic@beta` and let me know if you're still seeing issues?

**Comment by Fuiste** [comment]
This is a result of the relative newness of switch statements with strings in Java.  To avoid future issues, I've just cut a new release without the switch, `5.0.0-rc.1`.
