### ISSUE TITLE
 Failed to get absolute path to installed module

### ISSUE THREAD

**Issue by juuuhcteixeira** [ionic-team/cordova-plugin-ionic#96]
When I try to run this command

`cordova plugin add cordova-plugin-ionic --save \ --variable APP_ID="f8e67e79" \ --variable CHANNEL_NAME="Production" \ --variable UPDATE_METHOD="background"`

I got the following message

> Adding cordova-plugin-ionic to package.json
Saved plugin info for "cordova-plugin-ionic" to config.xml
(node:9092) UnhandledPromiseRejectionWarning: CordovaError: Failed to get absolute path to installed module
    at C:\Users\Julia\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:112:45
    at _rejected (C:\Users\Julia\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\Julia\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\Julia\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\Julia\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\Julia\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\Julia\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\Julia\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:9092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My infos are:

 cli packages: (C:\Users\Julia\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.3
    npm               : 6.2.0-next.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\Julia\AppData\Local\Android\Sdk

Misc:

    backend : pro

How can I fix it?

**Comment by media4learning** [comment]
You might need to install a platform first? 

ionic cordova platform add ios --save

Then try to install the ionic plugin. 

OR, you could also try to install a lower version of npm? 6.1.0 is the latest stable version, I have had trouble using the latest and greatest npm before.

**Comment by nphyatt** [comment]
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
