### ISSUE TITLE
Stuck in Splash Screen only in IOS real devices

### ISSUE THREAD

**Issue by white91wolf** [ionic-team/cordova-plugin-ionic#98]
HI,

i developed an app with ionic, angular and cordova. Now after debugging and testing on android i switched the code to a MAC to create/test the app on IOS devices. On the mac i added the ios plattform and build the project. in the created xcode project i added the developer team (for licence) and run it on an emulator for Iphone 8 - here all looked fine. So i took some real devices. The app is deploying and everything is fine but when the app starts on the device it stucks at the splash screen.

ionic info on the mac 
> 
> cli packages: (/usr/local/lib/node_modules)
> 
>     @ionic/cli-utils  : 1.19.2
>     ionic (Ionic CLI) : 3.20.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : 8.0.0 
> 
> local packages:
> 
>     @ionic/app-scripts : 3.1.9
>     Cordova Platforms  : ios 4.5.4
>     Ionic Framework    : ionic-angular 3.9.2
> 
> System:
> 
>     ios-deploy : 1.9.2 
>     ios-sim    : 6.1.2 
>     Node       : v8.7.0
>     npm        : 5.4.2 
>     OS         : macOS High Sierra
>     Xcode      : Xcode 9.4.1 Build version 9F2000 
> 
> Environment Variables:
> 
>     ANDROID_HOME : not set
> 
> Misc:
> 
>     backend : pro

used plugins are:

Plugins: 

> com.pylonproducts.wifiwizard,cordova-plugin-device,
> cordova-plugin-document-viewer,cordova-plugin-file,
> cordova-plugin-globalization,cordova-plugin-inappbrowser,
> cordova-plugin-ionic-keyboard,
> cordova-plugin-ionic-webview,
> cordova-plugin-nativeaudio,
> cordova-plugin-network-information,cordova-plugin-splashscreen,cordova-plugin-statusbar,
> cordova-plugin-whitelist,
> cordova-sqlite-storage,
> ionic-plugin-keyboard,
> phonegap-plugin-barcodescanner

in the console there is no suspicious output:

> Apache Cordova native platform version 4.5.3 is starting.
> Multi-tasking -> Device: YES, App: YES
> CDVWKWebViewEngine: trying to inject XHR polyfill
> CDVWKWebViewEngine will reload WKWebView if required on resume
> Using Ionic WKWebView
> [CDVTimer][console] 0.424981ms
> [CDVTimer][handleopenurl] 0.430942ms
> [CDVTimer][intentandnavigationfilter] 20.268083ms
> [CDVTimer][gesturehandler] 0.442982ms
> [CDVTimer][file] 17.497063ms
> [CDVTimer][keyboard] 6.814003ms
> [CDVTimer][splashscreen] 51.716089ms
> [CDVTimer][statusbar] 42.394996ms
> [CDVTimer][keyboard] 0.042081ms
> [CDVTimer][TotalPluginStartup] 144.748926ms
>

**Comment by white91wolf** [comment]
hi @nphyatt ,

here the informations:
cordova plugin ls

> com.pylonproducts.wifiwizard 0.2.11 "WifiWizard"
> cordova-plugin-device 2.0.2 "Device"
> cordova-plugin-document-viewer 0.9.10 "SitewaertsDocumentViewer"
> cordova-plugin-file 6.0.1 "File"
> cordova-plugin-globalization 1.11.0 "Globalization"
> cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
> cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
> cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
> cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
> cordova-plugin-network-information 2.0.1 "Network Information"
> cordova-plugin-splashscreen 5.0.2 "Splashscreen"
> cordova-plugin-statusbar 2.4.2 "StatusBar"
> cordova-plugin-whitelist 1.3.3 "Whitelist"
> cordova-sqlite-storage 2.3.1 "Cordova sqlite storage plugin"
> ionic-plugin-keyboard 2.2.1 "Keyboard"
> phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"

cordova platform ls

> Installed platforms:
>   android 7.0.0
>   ios 4.5.4
> Available platforms: 
>   browser ~5.0.1
>   osx ~4.0.1
>   windows ~5.0.0
>   www ^3.12.0

i got yesterday an other (real) iOS device (iPhone 7) and there the app works fine - the device i have trouble with is an iPad 3 with iOS 9.3.5. By default my app builds for target ios 9.0.0 thats why i thought it should work. So i apprehend that im using some plugin or something that needs a newer iOS version then 9.0.0.

**Comment by nphyatt** [comment]
So it doesn’t look like you’re using `cordova-plugin-Ionic` at all from what I can tell.  Just for reference this repo/plugin provides the “Live Updates” features for our [Ionic Pro](https://ionicframework.com/docs/pro/deploy/) product. It sounds like the issues you’re having are unrelated to that and this repository so I’ll be closing this issue. 

From what you’ve described however I would venture to guess you are correct in that one of your plugins may not support iOS 9.x.x. I believe at this point the percentage of Apple devices running iOS 9.x.x is in the low single digits so perhaps you could try targeting a higher version for iOS. If that’s not an option I’d suggest heading to our [community forums](https://forum.ionicframework.com) and looking for help there as we have a great community and hopefully you can find the solution to your issue. 

Thanks and good luck!
